// Order Reconstruction data model. Transient, in-memory reasoning over
// already-fetched email content — no persistence, no database table. This
// is deliberately a separate domain from lib/vinted's `purchases` table
// (explicit, user-confirmed import), which this does not touch.

// "confirmed" is reserved for forward-compatibility with the requested event
// vocabulary but is not emitted in v1: a classifySubject === "confirmation"
// email always produces a single "ordered" event, since there is no
// reliable signal in this codebase to distinguish "order placed" from
// "order confirmed by retailer" as two separate moments — they are almost
// always the same email, and fabricating two timeline entries from one
// source email would invent a fact that isn't there.
export type OrderEventType = "ordered" | "confirmed" | "dispatched" | "out_for_delivery" | "delivered" | "cancelled" | "returned" | "refund_processed" | "sold";
export type OrderStatus = OrderEventType | "unknown";

export type OrderEvent = { type: OrderEventType; date: string | null; sourceEmailId: string };

export type OrderItem = { name: string; quantity: number };

export type ReconstructedOrder = {
  orderId: string | null;
  merchant: string;
  purchaseDate: string | null;
  status: OrderStatus;
  // Content-derived hint layered on top of `status` — does not change what
  // status/timeline/grouping produce. See lib/orders/extract.ts's
  // looksLikePreorder: only ever set from confirmation-typed evidence, using
  // specific order-related phrases, never a bare "preorder" keyword match.
  isPreorder: boolean;
  // Selected via an evidence-priority strategy (lib/orders/reconstruct.ts),
  // never by summing the same item's quantity across different source
  // emails — a "1 x Product A" line repeated in a confirmation, its
  // cancellation, and its refund notice is one item, not three.
  items: OrderItem[];
  trackingNumbers: string[];
  // The price paid at checkout, extracted from a confirmation-typed email
  // (e.g. "Total paid £24.00") — distinct from refundAmount below. An order
  // can have one, both, or neither known: a refund being known does not
  // imply the purchase price is known, and vice versa. Keeping these as two
  // separate fields (rather than one generic "amount") is what lets
  // synthesis correctly say "I can't determine the purchase price, but a
  // refund of £X was issued" instead of conflating the two or claiming no
  // pricing information exists at all when one of the two is in fact known.
  purchaseAmount: number | null;
  refundAmount: number | null;
  currency: string | null;
  // May be empty; may contain more than one distinct card-ending — a refund
  // destination differing from the original payment card is real evidence,
  // not noise, so this is never collapsed down to a single value.
  paymentCards: string[];
  recipientName: string | null;
  // Deterministic, rule-based caveats generated by reconstruction itself
  // (e.g. "grouped by timing, not a shared order reference") — never
  // Claude-authored text.
  notes: string[];
  timeline: OrderEvent[];
  sourceEmails: string[];
  // Internal only — how the grouping was formed (shared order reference vs.
  // merchant+date-window heuristic vs. an orphaned single event). Used for
  // future debugging, testing, and UI work. Never shown to Claude (see
  // lib/orders/render.ts) and never sent to the browser (see
  // lib/orders/public.ts's toPublicOrder, which omits this and
  // `sourceEmails` from the API-facing DTO).
  confidence: number;
};

export type OrderSourceEmail = { id: string; sender: string; subject: string; date: string | null; text: string; html: string };
