"use client";
import { useEffect, useMemo, useState } from "react";

const conditions = ["Brand new", "Brand new without tags", "Labelled as very good condition", "Good condition from photos", "Decent condition from photos"];
type Candidate = { id:string; email_date:string; subject:string; order_reference:string|null; item_title:string|null; seller_name:string|null; item_size:string|null; price_paid:number|null; purchase_date:string|null; cancellation_refund_status:string|null; parser_confidence:number; import_status:string; imported_purchase_id:string|null; purchased_from:string|null; candidate_type:"vinted"|"general"; uncertainty_reasons:string[] };
type Edit = { selected:boolean; purchased_from:string; sku:string; item_description:string; seller_name:string; item_size:string; item_condition:string; price_purchased:string; order_date:string; arrived:""|"true"|"false" };

export default function PurchaseImportPage() {
  const today=new Date().toISOString().slice(0,10), monthAgo=new Date(Date.now()-30*86400000).toISOString().slice(0,10);
  const [startDate,setStart]=useState(monthAgo),[endDate,setEnd]=useState(today),[instruction,setInstruction]=useState(""),[rows,setRows]=useState<Candidate[]>([]),[edits,setEdits]=useState<Record<string,Edit>>({}),[filter,setFilter]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  async function load(){const r=await fetch("/api/vinted/candidates");if(!r.ok){const body=await r.json().catch(()=>({}));setError(body.error||"Could not load purchase candidates.");return}const data=await r.json();setRows(data);setEdits(old=>Object.fromEntries(data.map((x:Candidate)=>[x.id,old[x.id]||{selected:false,purchased_from:x.purchased_from||(x.candidate_type==="vinted"?"Vinted":""),sku:"",item_description:x.item_title||"",seller_name:x.candidate_type==="vinted"?(x.seller_name||""):"",item_size:x.item_size||(x.candidate_type==="general"?"N/A":""),item_condition:x.candidate_type==="general"?"Brand new":"",price_purchased:x.price_paid==null?"":String(x.price_paid),order_date:x.purchase_date||x.email_date.slice(0,10),arrived:""}])))}
  useEffect(()=>{load()},[]);
  async function sync(){setBusy(true);setError("");setMessage("Connecting to Yahoo and scanning…");try{const payload=instruction.trim()?{instruction:instruction.trim()}:{startDate,endDate};const r=await fetch("/api/vinted/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),body=await r.json();if(r.ok){setMessage(`Searched ${body.startDate} to ${body.endDate}. Scanned ${body.scanned} email headers; shortlisted ${body.shortlisted}; accepted ${body.parsed}; rejected ${body.rejected} non-purchases; ${body.uncertain||0} accepted emails need review.${body.truncated?" The mailbox scan reached its 5,000-email safety limit.":""}`);await load()}else setError(body.error||"Sync failed.")}catch{setError("The email search was interrupted. Please try again.")}finally{setBusy(false)}}
  async function removeCandidate(id:string){if(!confirm("Delete this candidate? The Yahoo email and any purchase will remain."))return;setBusy(true);const r=await fetch(`/api/vinted/candidates?id=${encodeURIComponent(id)}`,{method:"DELETE"}),body=await r.json();if(r.ok){setMessage("Candidate deleted. The Yahoo email was not changed.");await load()}else setError(body.error||"Could not delete candidate.");setBusy(false)}
  async function clearAll(){if(!confirm("Clear all unimported candidates? Yahoo emails and purchases will remain."))return;setBusy(true);const r=await fetch("/api/vinted/candidates?clear=all",{method:"DELETE"}),body=await r.json();if(r.ok){setMessage(`Cleared ${body.deleted} candidates.`);await load()}else setError(body.error||"Could not clear candidates.");setBusy(false)}
  function update(id:string,key:keyof Edit,value:string|boolean){setEdits(old=>({...old,[id]:{...old[id],[key]:value}}))}
  const visible=useMemo(()=>rows.filter(x=>!filter||`${x.subject} ${x.item_title} ${x.seller_name} ${x.order_reference} ${x.purchased_from}`.toLowerCase().includes(filter.toLowerCase())),[rows,filter]);
  const selectable=visible.filter(x=>x.import_status!=="imported"&&!x.cancellation_refund_status), allSelected=selectable.length>0&&selectable.every(x=>edits[x.id]?.selected);
  function toggleAll(){const ids=new Set(selectable.map(x=>x.id));setEdits(old=>Object.fromEntries(Object.entries(old).map(([id,e])=>[id,ids.has(id)?{...e,selected:!allSelected}:e])))}
  const chosen=visible.filter(x=>edits[x.id]?.selected&&x.import_status!=="imported"&&!x.cancellation_refund_status), invalid=chosen.filter(x=>{const e=edits[x.id];return !e.purchased_from||!e.item_description||!e.item_size||!e.item_condition||!e.price_purchased||!e.order_date}), total=chosen.reduce((n,x)=>n+(Number(edits[x.id]?.price_purchased)||0),0), duplicateCount=visible.filter(x=>x.import_status==="imported"||x.imported_purchase_id).length;
  async function importSelected(){if(!chosen.length||invalid.length)return;if(!confirm(`Import ${chosen.length} purchases totalling £${total.toFixed(2)}?`))return;setBusy(true);const records=chosen.map(x=>{const e=edits[x.id];return{candidateId:x.id,purchased_from:e.purchased_from,sku:e.sku,item_description:e.item_description,seller_name:e.seller_name,item_size:e.item_size,item_condition:e.item_condition,price_purchased:Number(e.price_purchased),order_date:e.order_date,arrived:e.arrived===""?null:e.arrived==="true"}});const r=await fetch("/api/vinted/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmed:true,records})}),body=await r.json();if(r.ok){setMessage(`Imported ${body.inserted}; duplicates excluded ${body.duplicates}; total £${body.total}.`);await load()}else setError(body.error||"Import failed.");setBusy(false)}
  return <section className="page-shell vinted-page"><header className="page-header"><div><span className="purchase-form-kicker">Yahoo Mail workflow</span><h1>Purchase Email Import</h1><p>Ask for purchases by retailer or date, review every result, then confirm.</p></div></header>
    <div className="card purchase-import-question"><label className="field"><span className="label">What purchases should I find?</span><textarea className="input" value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Import all my purchases from today, or import my Vinted purchases from last week."/></label><p>Leave this blank to use the exact dates below.</p></div>
    <div className="card sync-toolbar"><label className="field"><span className="label">From (optional)</span><input className="input" type="date" value={startDate} onChange={e=>setStart(e.target.value)}/></label><label className="field"><span className="label">To (optional)</span><input className="input" type="date" value={endDate} onChange={e=>setEnd(e.target.value)}/></label><button className="button" onClick={sync} disabled={busy}>{busy?"Syncing…":"Sync Yahoo"}</button></div>
    {message&&<p className="sync-message">{message}</p>}{error&&<p className="bulk-save-error">{error}</p>}
    <div className="data-panel"><div className="grid-toolbar"><input className="input" placeholder="Filter candidates" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="candidate-toolbar-actions"><span>{visible.length} candidates · {duplicateCount} duplicates</span>{selectable.length>0&&<button className="button-secondary" onClick={toggleAll}>{allSelected?"Deselect all":"Select all"}</button>}{rows.some(x=>x.import_status!=="imported")&&<button className="button-danger" onClick={clearAll}>Clear all</button>}</div></div>
      <div className="vinted-list">{visible.map(row=><CandidateRow key={row.id} row={row} edit={edits[row.id]} busy={busy} invalid={invalid.some(x=>x.id===row.id)} update={update} remove={removeCandidate}/>)}{!visible.length&&<div className="email-empty">No parsed candidates in this view.</div>}</div></div>
    <div className="bulk-save-bar"><div><strong>{chosen.length} selected · £{total.toFixed(2)}</strong><span>{invalid.length} with missing fields · {duplicateCount} duplicates excluded</span></div><button className="button" disabled={busy||!chosen.length||invalid.length>0} onClick={importSelected}>Review and confirm import</button></div>
  </section>
}

function CandidateRow({row,edit,busy,invalid,update,remove}:{row:Candidate;edit:Edit|undefined;busy:boolean;invalid:boolean;update:(id:string,key:keyof Edit,value:string|boolean)=>void;remove:(id:string)=>void}){
  if(!edit)return null;const disabled=row.import_status==="imported"||Boolean(row.cancellation_refund_status), uncertain=row.uncertainty_reasons||[];
  return <div className={`vinted-candidate ${disabled?"candidate-disabled":""}`}><div className="candidate-head"><input type="checkbox" checked={edit.selected} disabled={disabled} onChange={e=>update(row.id,"selected",e.target.checked)}/><div><strong>{row.item_title||row.subject}</strong><span>{row.order_reference||"No order reference"} · {new Date(row.email_date).toLocaleDateString()} · {row.candidate_type==="vinted"?"Vinted parser":"General parser"}</span></div><span className="confidence">{Math.round(row.parser_confidence*100)}% confidence</span>{uncertain.length>0&&<span className="uncertain-badge">Check details</span>}{disabled&&<span className="duplicate-badge">{row.cancellation_refund_status||"Already imported"}</span>}{row.import_status!=="imported"&&<button className="candidate-delete" onClick={()=>remove(row.id)} disabled={busy}>Delete</button>}</div>
    {uncertain.length>0&&<div className="candidate-uncertainty"><strong>I was unsure about this email:</strong><ul>{uncertain.map(x=><li key={x}>{x}</li>)}</ul></div>}
    <div className="candidate-grid"><Field label="Purchased from *" value={edit.purchased_from} set={v=>update(row.id,"purchased_from",v)}/><Field label="SKU" value={edit.sku} set={v=>update(row.id,"sku",v)} placeholder="May be blank"/><Field label="Item *" value={edit.item_description} set={v=>update(row.id,"item_description",v)}/><Field label="Seller" value={edit.seller_name} set={v=>update(row.id,"seller_name",v)} placeholder="May be blank"/><Field label="Size *" value={edit.item_size} set={v=>update(row.id,"item_size",v)}/><label>Condition *<select value={edit.item_condition} onChange={e=>update(row.id,"item_condition",e.target.value)}><option value="">Select manually</option>{conditions.map(x=><option key={x}>{x}</option>)}</select></label><label>Price *<input type="number" step=".01" min="0" value={edit.price_purchased} onChange={e=>update(row.id,"price_purchased",e.target.value)}/></label><label>Date *<input type="date" value={edit.order_date} onChange={e=>update(row.id,"order_date",e.target.value)}/></label><label>Arrived<select value={edit.arrived} onChange={e=>update(row.id,"arrived",e.target.value)}><option value="">Blank</option><option value="true">Yes</option><option value="false">No</option></select></label></div>{edit.selected&&invalid&&<p className="candidate-warning">Complete required fields. SKU and seller may remain blank.</p>}</div>
}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(value:string)=>void;placeholder?:string}){return <label>{label}<input value={value} placeholder={placeholder} onChange={e=>set(e.target.value)}/></label>}
