-- Run once in the Supabase SQL Editor before using Vault.
create extension if not exists pgcrypto;
create table if not exists public.vault_items(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,kind text not null check(kind in('note','link','file','guide','release','private')),title text not null check(char_length(title) between 1 and 300),folder text not null default 'Notes',tags text[] not null default '{}',content text not null default '',url text,release_date date,pinned boolean not null default false,private boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists vault_items_owner_updated_idx on public.vault_items(owner_id,pinned desc,updated_at desc);
create table if not exists public.vault_attachments(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,item_id uuid not null references public.vault_items(id) on delete cascade,name text not null,storage_path text not null unique,size bigint not null check(size>=0),mime_type text not null default 'application/octet-stream',created_at timestamptz not null default now());
create index if not exists vault_attachments_item_idx on public.vault_attachments(item_id,created_at);
alter table public.vault_items enable row level security;alter table public.vault_attachments enable row level security;
drop policy if exists "owner manages vault items" on public.vault_items;create policy "owner manages vault items" on public.vault_items for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
drop policy if exists "owner manages vault attachments" on public.vault_attachments;create policy "owner manages vault attachments" on public.vault_attachments for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
insert into storage.buckets(id,name,public,file_size_limit) values('vault-files','vault-files',false,52428800) on conflict(id) do update set public=false,file_size_limit=52428800;
drop policy if exists "owner accesses vault files" on storage.objects;create policy "owner accesses vault files" on storage.objects for all using(bucket_id='vault-files' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='vault-files' and (storage.foldername(name))[1]=auth.uid()::text);
