import { z } from "zod";
// Type-only — erased at compile time, matching lib/listing-studio/auto-group-schemas.ts's
// own convention exactly: keeps this file pure and directly testable with
// no Anthropic runtime import (and no server-only restriction), while still
// type-checking LISTING_GENERATION_TOOL against the SDK's own Tool shape.
import type Anthropic from "@anthropic-ai/sdk";

/**
 * Milestone 4 (AI listing generation). Deliberately NOT the 5-pass
 * image_quality/label_extraction/visual_identification/consistency_check/
 * generation pipeline sketched in lib/listing-studio/ai-schemas.ts during
 * Stage 1 planning (confirmed unused by any real route) — this is a single,
 * direct structured-extraction call per already-created product group,
 * modelled on lib/listing-studio/auto-group-schemas.ts's established
 * conventions (strict zod schema, forced single tool call, re-validated
 * regardless).
 *
 * Critically, the AI NEVER returns a title or description — only
 * structured product fields. Title/description are always derived from
 * those fields by lib/listing-studio/listing-template.ts's pure functions,
 * never generated by, or independently editable from, the AI's own output.
 */

const fieldValueSchema = z.string().trim().min(1).max(150).nullable();
const confidenceSchema = z.enum(["high", "medium", "low"]);
const notesSchema = z.string().trim().min(1).max(500).nullable();

function structuredField<T extends z.ZodTypeAny>(valueSchema: T) {
  return z.object({ value: valueSchema, confidence: confidenceSchema }).strict();
}

// Milestone 4 sizing correction: the AI must never perform or invent a
// size-system conversion itself (lib/listing-studio/size-conversion.ts is
// the ONE place that happens, deterministically, brand-aware). This field
// bundles exactly what the model is allowed to report — which system was
// printed on the label, its raw value, and (only if the label itself
// states it) which gender — as one unit, since all three describe the same
// single size marking read off the same label. `system`/`value` are kept
// independently nullable (rather than requiring both-or-neither) so a
// response that's otherwise perfectly good isn't rejected outright over an
// inconsistent size read; the caller treats a partial pair (one set,
// the other null) as "no usable source size" rather than guessing.
// Milestone 4 sizing coverage correction: `gender` gained a 4th value,
// "childrens" — children's footwear uses an entirely different numbering
// scale from adult sizing (see lib/listing-studio/size-conversion.ts), so
// this must be reported explicitly rather than silently treated as an
// adult size. Still only ever reported when the label itself states it
// (e.g. "Kids"/"Youth"/"Toddler" wording, or a children's-specific size
// range) — never inferred from the shoe's general style.
const sourceSizeSchema = z.object({
  system: z.enum(["UK", "EU", "US"]).nullable(),
  value: z.string().trim().min(1).max(20).nullable(),
  gender: z.enum(["mens", "womens", "unisex", "childrens"]).nullable(),
  confidence: confidenceSchema,
}).strict();
export type SourceSize = z.infer<typeof sourceSizeSchema>;

export const listingGenerationFieldsSchema = z.object({
  brand: structuredField(fieldValueSchema),
  model: structuredField(fieldValueSchema),
  productType: structuredField(fieldValueSchema),
  colour: structuredField(fieldValueSchema),
  sourceSize: sourceSizeSchema,
  sku: structuredField(fieldValueSchema),
  notes: notesSchema,
}).strict();
export type ListingGenerationFields = z.infer<typeof listingGenerationFieldsSchema>;

export const LISTING_GENERATION_SYSTEM_PROMPT =
  "You extract structured product data for ONE physical product from every photo of it, for a resale listing tool, using the propose_listing_fields tool. You must call that tool exactly once. Never return a title, a description, or any free-form prose — only the structured fields the tool defines; the application generates the actual listing title and description from those fields itself. "
  + "BRAND: identify the manufacturer only from clear visible evidence in the photos (a logo, label, or embossed marking) — for example Nike, Adidas, On, ASICS, New Balance, Hoka, Birkenstock. Never invent a brand you cannot see evidence for — if genuinely unclear, leave the value null. "
  + "MODEL / SILHOUETTE: the specific model or silhouette name, for example Cloudmonster, Cloud 5, Gel Kayano 14, Pegasus Trail 5, Arizona, Boston. If you cannot confidently identify it, leave the value null — never guess. "
  + "PRODUCT TYPE: a generic product type, for example Running Trainers, Trail Running Trainers, Walking Shoes, Sandals, Slides, Football Boots. "
  + "COLOUR: either a plain description joining the visible colours with \"&\" (for example \"White & Blue\"), or the official colourway name ONLY if you confidently recognise it (for example \"Solar Red\", \"OG Neon\") — never guess an official colourway name; a plain colour description is always the safer choice when unsure. "
  + "SIZE: read whichever size marking is printed on the label — report it in sourceSize, exactly as printed, in only ONE system. If a UK size is clearly printed (for example \"UK 9\", \"UK9\"), report system \"UK\" with that value — always prefer a directly printed UK size over any EU or US size shown on the very same label, even when more than one system is printed together. Only if no UK size is visible anywhere: if a EU size is clearly printed (for example \"EU 44\", \"42.5\"), report system \"EU\" with that value. Only if neither UK nor EU is visible: if a US size is clearly printed (for example \"US 10\", \"M 10\"), report system \"US\" with that value. You must NEVER convert between sizing systems yourself, and never write a converted value — the application does that separately, deterministically. If the label itself indicates whether this is a men's, women's, or unisex size (for example a printed \"M\"/\"W\"/\"Mens\"/\"Womens\", or two separate size columns on the same label), report that as sourceSize.gender — leave gender null if the label doesn't state it; never guess gender from the shoe's general style or appearance. Only report sourceSize.gender as \"childrens\" when the label or packaging itself explicitly says so — wording like \"Kids\", \"Youth\", \"Toddler\", \"Infant\", or a size clearly printed in a children's-specific range (for example \"UK 10.5\" alongside a \"Kids\" label) — never inferred just because the shoe looks small or youth-styled. If different photos of this product show conflicting size information (labels that disagree with each other), or you cannot confidently read any size marking at all, leave sourceSize.system and sourceSize.value both null rather than picking one. "
  + "SKU: read the white inventory sticker inside the shoe, for example 1648, 1672, 1728 — search every single photo you are shown for it, since it may only be visible in one. If more than one sticker is visible and they disagree with each other, or none can be found at all, leave the value null. Never invent a SKU. "
  + "For every field, also report your own confidence: \"high\" only when you are genuinely certain, \"medium\" when reasonably confident but not fully certain, \"low\" for a weak guess. Prefer leaving a value null over a low-confidence guess, especially for model, colour, sourceSize, and SKU. "
  + "Use notes only for a brief remark about something genuinely ambiguous or uncertain about this product (for example conflicting SKU stickers, conflicting size labels, or a partly obscured label) — leave notes null otherwise, never pad it with a description of what you saw.";

export const LISTING_GENERATION_TOOL: Anthropic.Tool = {
  name: "propose_listing_fields",
  description: "Report the structured product fields (brand, model, product type, colour, source size, SKU) identified from this one product's photos. Call this exactly once. Never include a title, description, or a converted size — only the size exactly as printed on the label.",
  input_schema: {
    type: "object",
    properties: {
      brand: {
        type: "object",
        properties: { value: { type: ["string", "null"] }, confidence: { type: "string", enum: ["high", "medium", "low"] } },
        required: ["value", "confidence"], additionalProperties: false,
      },
      model: {
        type: "object",
        properties: { value: { type: ["string", "null"] }, confidence: { type: "string", enum: ["high", "medium", "low"] } },
        required: ["value", "confidence"], additionalProperties: false,
      },
      productType: {
        type: "object",
        properties: { value: { type: ["string", "null"] }, confidence: { type: "string", enum: ["high", "medium", "low"] } },
        required: ["value", "confidence"], additionalProperties: false,
      },
      colour: {
        type: "object",
        properties: { value: { type: ["string", "null"] }, confidence: { type: "string", enum: ["high", "medium", "low"] } },
        required: ["value", "confidence"], additionalProperties: false,
      },
      sourceSize: {
        type: "object",
        properties: {
          system: { type: ["string", "null"], enum: ["UK", "EU", "US", null], description: "The size system exactly as printed on the label — UK preferred if visible, then EU, then US. Never a converted system." },
          value: { type: ["string", "null"], description: "The size value exactly as printed, in the reported system only. Never converted." },
          gender: { type: ["string", "null"], enum: ["mens", "womens", "unisex", "childrens", null], description: "Only if the label itself states it (e.g. \"Kids\"/\"Youth\"/\"Toddler\" wording or a children's-specific size range). Null if not stated — never guessed, and never inferred from the shoe's general style." },
          confidence: { type: "string", enum: ["high", "medium", "low"] },
        },
        required: ["system", "value", "gender", "confidence"], additionalProperties: false,
      },
      sku: {
        type: "object",
        properties: { value: { type: ["string", "null"] }, confidence: { type: "string", enum: ["high", "medium", "low"] } },
        required: ["value", "confidence"], additionalProperties: false,
        description: "Read from the white inventory sticker inside the shoe. Null if unreadable, absent, or disagreeing stickers.",
      },
      notes: { type: ["string", "null"], description: "A brief note about genuine ambiguity/uncertainty only. Null otherwise." },
    },
    required: ["brand", "model", "productType", "colour", "sourceSize", "sku", "notes"],
    additionalProperties: false,
  },
} as const;

/** Every way the listing-generation AI call can end — mirrors AutoGroupAiOutcome's
 * closed-set convention exactly, so a failure is always a safe, fixed,
 * pre-written category, never a raw provider error surfaced to the UI. */
export type ListingGenerationAiOutcome =
  | { status: "success"; data: ListingGenerationFields }
  | { status: "not_configured" }
  | { status: "request_failed" }
  | { status: "no_tool_call" }
  | { status: "invalid_output" };

export function describeListingGenerationFailure(status: Exclude<ListingGenerationAiOutcome["status"], "success">): string {
  switch (status) {
    case "not_configured": return "Listing generation is not available right now.";
    case "request_failed": return "Listing generation failed. Please try again.";
    case "no_tool_call": return "Listing generation did not return a structured result. Please try again.";
    case "invalid_output": return "Listing generation returned an unexpected result. Please try again.";
  }
}
