import { describe, expect, it } from "vitest"; import { canonicalSender, countSubjectTerms, isExactEmailAddress, searchVariants, semanticSubjectTerms, senderSearchVariants } from "@/lib/yahoo/search-terms";
describe("forgiving mailbox terms",()=>{
  it("expands UK/US centre spelling and accented Pokémon",()=>{const values=searchVariants(["pokemon centre"]);expect(values).toContain("pokemon centre");expect(values).toContain("pokemon center");expect(values).toContain("pokémon centre");expect(values).toContain("pokémon center");});
  it("keeps unrelated terms unchanged and bounded",()=>{expect(searchVariants(["holiday booking"])).toEqual(["holiday booking"]);expect(searchVariants(Array.from({length:20},(_,i)=>`term ${i}`))).toHaveLength(12);});
  it("expands order-confirmation intent without requiring an exact subject",()=>{const values=searchVariants(["order confirmation"]);expect(values).toContain("your order");expect(values).toContain("order received");expect(values).toContain("receipt");});
  it("canonicalizes a misspelled accented sender name",()=>{expect(canonicalSender("Pokemon Centre")).toBe("pokémon center");});
  it("recognizes order lifecycle intent independently of retailer",()=>{expect(semanticSubjectTerms(["order confirmation"])).toContain("order");expect(semanticSubjectTerms(["find my receipt"])).toContain("invoice");expect(semanticSubjectTerms(["tracking update"])).toContain("tracking");expect(semanticSubjectTerms(["delivery notice"])).toContain("delivered");expect(semanticSubjectTerms(["cancelled order"])).toContain("cancellation");expect(semanticSubjectTerms(["refund update"])).toContain("refunded");});
  it("treats standalone purchase and order words as semantic intent",()=>{expect(semanticSubjectTerms(["purchase"])).toContain("order");expect(semanticSubjectTerms(["latest order"])).toContain("receipt");});
  it("searches receipt requests using retailer confirmation wording",()=>{const terms=semanticSubjectTerms(["latest receipt"]);expect(terms).toContain("confirmed");expect(terms).toContain("confirmation");});
  it("counts the broad vocabulary retailers use for transactions",()=>{const terms=semanticSubjectTerms(["order confirmations"]);for(const term of ["purchase","receipt","order details","payment received","order"])expect(terms).toContain(term);});
  it("does not count preorder promotions as order confirmations",()=>{const terms=semanticSubjectTerms(["order confirmations"]);expect(terms).not.toContain("preorder");expect(terms.slice(0,3)).toEqual(["confirmed","confirmation","thank you for"]);});
  it("does not treat generic order wording as proof of confirmation",()=>{const terms=countSubjectTerms(["order confirmations"]);expect(terms).not.toContain("order");expect(terms).toContain("order details");expect(terms).toContain("purchase");expect(terms).toContain("receipt");});
  it("prioritizes confirmation wording over generic order wording",()=>{expect(semanticSubjectTerms(["latest order confirmation"]).slice(0,3)).toEqual(["confirmed","confirmation","thank you for"]);});
  it("accepts the common conformation typo",()=>{expect(semanticSubjectTerms(["latest order conformation"]).slice(0,3)).toEqual(["confirmed","confirmation","thank you for"]);});
  it("creates bounded typo-tolerant sender probes in useful order",()=>{const values=senderSearchVariants("Pokmon Cnter");expect(values.slice(0,3)).toEqual(["Pokmon Cnter","pokm","cnte"]);expect(senderSearchVariants("assos").slice(0,3)).toContain("asos");expect(values.length).toBeLessThanOrEqual(12);});
  it("uses strict sender matching only for literal email addresses",()=>{expect(isExactEmailAddress("orders@example.test")).toBe(true);expect(isExactEmailAddress("ASOS Sample Sale")).toBe(false);expect(isExactEmailAddress("ASOS")).toBe(false);});
  it("still recognizes sold-intent wording used by semanticSubjectTerms",()=>{expect(semanticSubjectTerms(["Vinted sold emails"])).toContain("you’ve sold");});
});
