import { describe, expect, it } from "vitest"; import { readFileSync } from "node:fs"; import { globSync } from "node:fs";
const read=(path:string)=>readFileSync(path,"utf8");
describe("server security boundaries",()=>{
  it("protects every API route with owner authorization",()=>{const routes=globSync("app/api/**/route.ts");expect(routes.length).toBeGreaterThan(10);for(const route of routes)expect(read(route),route).toContain("requireOwner");});
  it("opens Yahoo mail read-only and always releases locks/connections",()=>{const source=read("lib/yahoo/client.ts");expect(source).toContain("readOnly: true");expect(source).toContain("finally");expect(source).not.toMatch(/\.messageDelete|\.messageMove|\.messageFlagsAdd|\.append\(/);});
  it("counts and deduplicates email identifiers without fetching message bodies",()=>{const source=read("lib/yahoo/client.ts");const counter=source.slice(source.indexOf("export async function countYahoo"),source.indexOf("export type YahooMetadata"));expect(counter).toContain("countQueries(criteria)");expect(counter).toContain("new Set<number>()");expect(counter).not.toContain("fetchAll");expect(counter).not.toContain("simpleParser");});
  it("validates count candidates using envelope subjects only",()=>{const source=read("lib/yahoo/client.ts");const counter=source.slice(source.indexOf("export async function countYahoo"),source.indexOf("export type YahooMetadata"));expect(counter).toContain("classifyIndexedEmail(message.envelope?.subject");expect(counter).toContain("{ envelope: true }");expect(counter).not.toContain("source:");});
  it("allows forwarded and aliased lifecycle mail to match the named company",()=>{const source=read("lib/yahoo/client.ts");const queries=source.slice(source.indexOf("function countQueries"),source.indexOf("function address"));expect(queries).toContain("base.text = canonicalSender(criteria.sender)");expect(queries).not.toContain("base.from = canonicalSender(criteria.sender)");});
  it("indexes envelope metadata without fetching message source",()=>{const source=read("lib/yahoo/client.ts");const scanner=source.slice(source.indexOf("export async function scanYahooMetadata"),source.indexOf("export async function getYahooEmail"));expect(scanner).toContain("envelope: true");expect(scanner).not.toContain("source:");expect(scanner).not.toContain("simpleParser");});
  it("does not search outgoing or deleted folders for received mail",()=>{const source=read("lib/yahoo/client.ts");expect(source.match(/sent\|drafts\?\|spam\|junk\|trash/g)?.length).toBeGreaterThanOrEqual(2);});
  it("stops mailbox searching once the requested result page is full",()=>{const source=read("lib/yahoo/client.ts");expect(source).toContain("const candidateTarget = Math.min(100, offset + criteria.maxResults)");expect(source).toContain("matched.size >= candidateTarget");expect(source).toContain("candidates.length >= candidateTarget");});
  it("requires explicit confirmed imports and database idempotency constraints",()=>{expect(read("app/api/vinted/import/route.ts")).toContain("z.literal(true)");const migration=read("supabase-yahoo-email-agent.sql");expect(migration).toContain("purchases_vinted_candidate_unique");expect(migration).toContain("purchases_vinted_reference_unique");expect(migration).toContain("purchases_vinted_fingerprint_unique");});
  it("keeps imported candidates for duplicate prevention but hides them from review",()=>{const source=read("app/api/vinted/candidates/route.ts");expect(source).toContain("import_status=neq.imported");expect(source).toContain("import_status=neq.imported&select=id");});
  it("keeps credentials in server environment variables",()=>{const env=read(".env.example");for(const name of ["YAHOO_APP_PASSWORD","ANTHROPIC_API_KEY","SUPABASE_SECRET_KEY","EMAIL_ID_SECRET"])expect(env).toMatch(new RegExp(`^${name}=$`,"m"));expect(read("lib/yahoo/client.ts")).toContain('import "server-only"');expect(read("lib/anthropic/assistant.ts")).toContain('import "server-only"');});
});
