import { describe, expect, it } from "vitest"; import { parseVintedEmail } from "@/lib/vinted/parser";
const base={messageId:"<anon-123@example.test>",sender:"Vinted <orders@email.vinted.com>",date:"2026-07-10T10:00:00.000Z"};
describe("deterministic Vinted parser",()=>{
  it("extracts a genuine purchase without inventing condition or SKU",()=>{const row=parseVintedEmail({...base,subject:"Your purchase is confirmed",text:"Order number: AB-12345\nItem: Blue jacket\nSeller: sample_seller\nSize: M\nTotal: £18.50"});expect(row).toMatchObject({order_reference:"AB-12345",item_title:"Blue jacket",seller_name:"sample_seller",item_size:"M",price_paid:18.5});expect(row).not.toHaveProperty("sku");expect(row).not.toHaveProperty("item_condition");});
  it.each(["Your order was dispatched","Your order was delivered","Your order was cancelled","Your payment was refunded","Your payment is being sent to your bank","This order is completed"])("rejects non-purchase lifecycle mail: %s",subject=>{expect(parseVintedEmail({...base,messageId:`<${subject}@example.test>`,subject,text:"Order number: AB-12345"})).toBeNull();});
  it("rejects unknown formats and non-Vinted senders",()=>{expect(parseVintedEmail({...base,subject:"Newsletter",text:"Hello"})).toBeNull();expect(parseVintedEmail({...base,sender:"attacker@example.test",subject:"Your purchase",text:"Order: 12345"})).toBeNull();});
  it("rejects seller-side sale and shipping notifications",()=>{expect(parseVintedEmail({...base,subject:"You’ve sold an item on Vinted",text:"Payment received. Make sure to send your item to the buyer."})).toBeNull();expect(parseVintedEmail({...base,messageId:"<sale-2@example.test>",subject:"Your item has sold",text:"Order number: SALE-123"})).toBeNull();});
  it("parses an iCloud-forwarded Vinted receipt after table text is collapsed",()=>{const row=parseVintedEmail({messageId:"<receipt@example.test>",sender:"iCloud <noreply@icloud.example>",subject:'Your receipt for “Anonymised Running Shoe”',date:"2026-06-09T20:15:00.000Z",text:"Your payment has been received. Your Vinted purchase receipt: Seller sample_seller Order Anonymised Running Shoe Paid £14.19 Item £10.00 Postage £2.99 Buyer Protection fee £1.20 Payment date 09/06/2026 20:09 Transaction ID 2030000000"});expect(row).toMatchObject({order_reference:"2030000000",item_title:"Anonymised Running Shoe",seller_name:"sample_seller",price_paid:14.19,purchase_date:"2026-06-09"});});
  it("creates a stable conservative fallback fingerprint",()=>{const input={...base,subject:"Purchase confirmed",text:"Item: Coat\nSeller: seller_a\nTotal: £20"};expect(parseVintedEmail(input)?.fingerprint).toBe(parseVintedEmail(input)?.fingerprint);});
});
