import { describe, expect, it } from "vitest";
import {
  createInitialState, applyClaim, applyBatchPayload, nextQueuedItem, allItemsTerminal, isBatchActive,
  applyItemStatus, applyItemAttemptStarting, applyItemCompleted, applyItemFailed, applyCancelRemaining,
  applyRetryItem, applyStart, applyPause, applyResume,
  applyAccountDetected, applyAccountConfirmed, applyAccountChangeConfirmed, ACCOUNT_IDENTIFICATION_ERROR,
  applySelectedVintedTab, applyVintedTabLost, isVintedTabLostPause, VINTED_TAB_LOST_MESSAGE,
  resumeAfterRestart, computeProgressSummary, isBatchExpired, ITEM_STATUSES, isTerminalStatus,
  applyPendingSaveStarted, applyPendingSaveConfirmed, applyPendingSaveCheckAttempted, applyPendingSaveExpired,
  isPendingSaveExpired, SAVE_DRAFT_UNCONFIRMED_ERROR_CODE, SAVE_DRAFT_UNCONFIRMED_MESSAGE,
  applyPendingSaveTabReacquired,
  applyManualReloadNeeded, applyManualReloadAttempt, applyManualReloadTabReacquired, applyManualReloadResolved,
  isManualReloadPause, MANUAL_RELOAD_WARNING_MESSAGE,
} from "../vinted-draft-queue-extension/shared/queue-state.js";

const T0 = "2026-08-05T10:00:00.000Z";
const T1 = "2026-08-05T10:01:00.000Z";

function payload(overrides: Record<string, unknown> = {}) {
  return {
    schemaVersion: "vinted-extension-batch-v1", batchId: "batch-1", expiresAt: "2026-08-05T10:10:00.000Z",
    items: [
      { itemId: "item-1", draftId: "draft-1", queuePosition: 0, title: "Hoka Clifton 9", sku: "AA1" },
      { itemId: "item-2", draftId: "draft-2", queuePosition: 1, title: "Nike Air Max", sku: "AA2" },
    ],
    ...overrides,
  };
}

const IDENTITY_A = { memberId: "1001", displayName: "shopfront_uk" };

/** A freshly-claimed batch with its account already detected AND confirmed — the state most tests outside the account-confirmation suite itself actually want, since applyStart() now refuses to run without it. */
function confirmedBatchState() {
  let state = applyBatchPayload(createInitialState(), payload(), T0);
  state = applyAccountDetected(state, IDENTITY_A, T0);
  return applyAccountConfirmed(state, T0);
}

describe("createInitialState / applyClaim", () => {
  it("starts with no pairing and no batch", () => {
    expect(createInitialState()).toEqual({ pairing: null, batch: null });
  });
  it("applyClaim sets pairing without touching batch", () => {
    const state = applyClaim(createInitialState(), { batchId: "batch-1", batchToken: "tok", expiresAt: "exp", claimedAt: T0 });
    expect(state.pairing).toEqual({ batchId: "batch-1", batchToken: "tok", expiresAt: "exp", claimedAt: T0 });
    expect(state.batch).toBeNull();
  });
});

describe("applyBatchPayload", () => {
  it("populates items in queuePosition order, all starting QUEUED", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(state.batch!.items.map((i: any) => i.itemId)).toEqual(["item-1", "item-2"]);
    expect(state.batch!.items.every((i: any) => i.status === ITEM_STATUSES.QUEUED)).toBe(true);
    expect(state.batch!.running).toBe(false);
  });

  it("REGRESSION: re-fetching the same batch's payload preserves already-progressed item status/attemptCount — never resets real progress", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemCompleted(state, "item-1", "999", T1);
    const refetched = applyBatchPayload(state, payload(), T1);
    const item1 = refetched.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item1.status).toBe(ITEM_STATUSES.COMPLETED);
    expect(item1.vintedDraftId).toBe("999");
  });

  it("REGRESSION (payload-loss fix): a refetch preserves queue-controlled progress (status/attemptCount/errors/lastProgressAt) while refreshing every other payload field — never stale, never corrupted", () => {
    const fullItem = {
      itemId: "item-1", draftId: "draft-1", queuePosition: 0, title: "Hoka Clifton 9", sku: "AA1",
      description: "d1", brand: "b1", model: null, productType: "trainers", condition: "very_good",
      ukSize: "9", audience: "men", colours: ["black"], materials: ["mesh"],
      pricePence: 1000, priceDisplay: "£10.00", vintedCategoryId: 1, vintedCategoryPath: "Men > Shoes",
      photos: [{ position: 0, path: "/api/extension/batch/photos/item-1/0", fileName: "01.jpg" }], coverPhotoPosition: 0,
    };
    let state = applyBatchPayload(createInitialState(), payload({ items: [fullItem, payload().items[1]] }), T0);
    state = applyItemAttemptStarting(state, "item-1", T0); // "preparing", attemptCount 1
    state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.FILLING }, T1);

    const refreshedItem = { ...fullItem, description: "d2 (regenerated by the app)", pricePence: 2000, priceDisplay: "£20.00" };
    const refetched = applyBatchPayload(state, payload({ items: [refreshedItem, payload().items[1]] }), T1);
    const item1 = refetched.batch!.items.find((i: any) => i.itemId === "item-1")!;

    expect(item1.status).toBe(ITEM_STATUSES.FILLING); // progress preserved
    expect(item1.attemptCount).toBe(1);
    expect(item1.lastProgressAt).toBe(T1);
    expect(item1.description).toBe("d2 (regenerated by the app)"); // payload refreshed, not stale
    expect(item1.pricePence).toBe(2000);
    expect(item1.brand).toBe("b1"); // untouched fields still present, never discarded
  });

  it("sorts items by queuePosition even if the payload's own array order differs", () => {
    const shuffled = payload({ items: [
      { itemId: "item-2", draftId: "draft-2", queuePosition: 1, title: "b", sku: null },
      { itemId: "item-1", draftId: "draft-1", queuePosition: 0, title: "a", sku: null },
    ] });
    const state = applyBatchPayload(createInitialState(), shuffled, T0);
    expect(state.batch!.items.map((i: any) => i.itemId)).toEqual(["item-1", "item-2"]);
  });
});

describe("nextQueuedItem / allItemsTerminal / isBatchActive", () => {
  it("returns the first QUEUED item", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(nextQueuedItem(state)!.itemId).toBe("item-1");
  });
  it("returns null once nothing is queued", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemCompleted(state, "item-1", "1", T0);
    state = applyItemCompleted(state, "item-2", "2", T0);
    expect(nextQueuedItem(state)).toBeNull();
  });
  it("allItemsTerminal is true only when every item is completed/failed/cancelled", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(allItemsTerminal(state.batch!.items)).toBe(false);
    state = applyItemCompleted(state, "item-1", "1", T0);
    state = applyItemFailed(state, "item-2", "SAVE_DRAFT", "nope", T0);
    expect(allItemsTerminal(state.batch!.items)).toBe(true);
  });
  it("isBatchActive is false once every item is terminal, and false when there's no batch at all", () => {
    expect(isBatchActive(createInitialState())).toBe(false);
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(isBatchActive(state)).toBe(true);
    state = applyItemCompleted(state, "item-1", "1", T0);
    state = applyItemCompleted(state, "item-2", "2", T0);
    expect(isBatchActive(state)).toBe(false);
  });
});

describe("applyItemStatus / applyItemAttemptStarting / applyItemCompleted / applyItemFailed", () => {
  it("applyItemStatus merges fields into exactly one item, others untouched", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    const next = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.FILLING });
    expect(next.batch!.items[0].status).toBe(ITEM_STATUSES.FILLING);
    expect(next.batch!.items[1].status).toBe(ITEM_STATUSES.QUEUED);
  });
  it("is a safe no-op for an unknown itemId — returns the same reference", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyItemStatus(state, "does-not-exist", { status: ITEM_STATUSES.FAILED })).toBe(state);
  });
  it("applyItemAttemptStarting bumps attemptCount and sets startedAt only on the FIRST attempt", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemAttemptStarting(state, "item-1", T0);
    expect(state.batch!.items[0].attemptCount).toBe(1);
    expect(state.batch!.items[0].startedAt).toBe(T0);
    state = applyItemAttemptStarting(state, "item-1", T1);
    expect(state.batch!.items[0].attemptCount).toBe(2);
    expect(state.batch!.items[0].startedAt).toBe(T0); // unchanged on retry
  });
  it("applyItemCompleted sets status/vintedDraftId/completedAt and clears any error", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemFailed(state, "item-1", "SAVE_DRAFT", "boom", T0);
    state = applyItemCompleted(state, "item-1", "555", T1);
    const item = state.batch!.items[0];
    expect(item.status).toBe(ITEM_STATUSES.COMPLETED);
    expect(item.vintedDraftId).toBe("555");
    expect(item.errorCode).toBeNull();
    expect(item.errorMessage).toBeNull();
  });
  it("applyItemFailed records the error code/message and completedAt", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemFailed(state, "item-1", "SET_CATEGORY", "ambiguous", T1);
    const item = state.batch!.items[0];
    expect(item.status).toBe(ITEM_STATUSES.FAILED);
    expect(item.errorCode).toBe("SET_CATEGORY");
    expect(item.errorMessage).toBe("ambiguous");
    expect(item.completedAt).toBe(T1);
  });

  // Follow-up correction (live-investigation diagnostics gap) — a fresh
  // item starts with no step progress tracked at all; each stage of that
  // tracking (fresh item, in-progress, succeeded-then-failed, completed,
  // retried) is proven independently below.
  describe("currentStep / lastCompletedStep — field-level progress tracking", () => {
    it("a freshly queued item starts with both null", () => {
      const state = applyBatchPayload(createInitialState(), payload(), T0);
      expect(state.batch!.items[0].currentStep).toBeNull();
      expect(state.batch!.items[0].lastCompletedStep).toBeNull();
    });

    it("applyItemStatus carries currentStep/lastCompletedStep through when given, exactly like every other field", () => {
      let state = applyBatchPayload(createInitialState(), payload(), T0);
      state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.FILLING, currentStep: "SET_PRICE", lastCompletedStep: "SET_MATERIALS" }, T0);
      expect(state.batch!.items[0].currentStep).toBe("SET_PRICE");
      expect(state.batch!.items[0].lastCompletedStep).toBe("SET_MATERIALS");
    });

    it("applyItemAttemptStarting resets both to null — a retry never shows a step as already completed before it has actually re-run", () => {
      let state = applyBatchPayload(createInitialState(), payload(), T0);
      state = applyItemStatus(state, "item-1", { currentStep: "SET_PRICE", lastCompletedStep: "SET_MATERIALS" }, T0);
      state = applyItemAttemptStarting(state, "item-1", T1);
      expect(state.batch!.items[0].currentStep).toBeNull();
      expect(state.batch!.items[0].lastCompletedStep).toBeNull();
    });

    it("applyItemFailed clears currentStep (nothing is 'currently' running once terminal) but PRESERVES lastCompletedStep from the last progress report — showing exactly how far it got before failing", () => {
      let state = applyBatchPayload(createInitialState(), payload(), T0);
      state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.FILLING, currentStep: "SET_PRICE", lastCompletedStep: "SET_MATERIALS" }, T0);
      state = applyItemFailed(state, "item-1", "SET_PRICE", "TIMEOUT: step=SET_PRICE ...", T1);
      const item = state.batch!.items[0];
      expect(item.currentStep).toBeNull();
      expect(item.lastCompletedStep).toBe("SET_MATERIALS"); // exactly how far it got — SET_PRICE (errorCode) is the failed step, SET_MATERIALS is the last one that actually succeeded
      expect(item.errorCode).toBe("SET_PRICE"); // the failed step — doubles as "failedStep", no separate field needed
    });

    it("applyItemFailed accepts an EXPLICIT lastCompletedStep from the caller, taking precedence over whatever was already persisted", () => {
      let state = applyBatchPayload(createInitialState(), payload(), T0);
      state = applyItemStatus(state, "item-1", { lastCompletedStep: "SET_BRAND" }, T0);
      state = applyItemFailed(state, "item-1", "SET_SIZE", "boom", T1, "SET_CATEGORY");
      expect(state.batch!.items[0].lastCompletedStep).toBe("SET_CATEGORY");
    });

    it("applyItemCompleted clears currentStep — nothing is 'currently' running once the item is done", () => {
      let state = applyBatchPayload(createInitialState(), payload(), T0);
      state = applyItemStatus(state, "item-1", { currentStep: "SAVE_DRAFT", lastCompletedStep: "SET_PRICE" }, T0);
      state = applyItemCompleted(state, "item-1", "999", T1);
      expect(state.batch!.items[0].currentStep).toBeNull();
    });
  });
});

describe("applyCancelRemaining — cooperative cancel: never interrupts an in-flight item", () => {
  it("cancels only QUEUED items", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemAttemptStarting(state, "item-1", T0); // now "preparing" — in flight
    state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.FILLING });
    state = applyCancelRemaining(state);
    expect(state.batch!.items[0].status).toBe(ITEM_STATUSES.FILLING); // untouched — in flight
    expect(state.batch!.items[1].status).toBe(ITEM_STATUSES.CANCELLED); // was queued
    expect(state.batch!.running).toBe(false);
  });
});

describe("applyRetryItem", () => {
  it("resets a failed item back to QUEUED and clears its error", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemFailed(state, "item-1", "SET_PRICE", "boom", T0);
    state = applyRetryItem(state, "item-1");
    const item = state.batch!.items[0];
    expect(item.status).toBe(ITEM_STATUSES.QUEUED);
    expect(item.errorCode).toBeNull();
    expect(item.errorMessage).toBeNull();
  });
});

describe("applyStart / applyPause / applyResume", () => {
  it("REGRESSION: applyStart is a safe no-op — never starts the batch — when no account has been confirmed yet", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0); // no account detected/confirmed at all
    const started = applyStart(state);
    expect(started).toBe(state); // unchanged reference — a true no-op
    expect(started.batch!.running).toBe(false);
  });

  it("REGRESSION: applyStart is still a safe no-op when an account has been detected but not yet explicitly confirmed", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyAccountDetected(state, IDENTITY_A, T0); // pendingConfirmation set, but no confirm click yet
    const started = applyStart(state);
    expect(started.batch!.running).toBe(false);
  });

  it("applyStart sets running true and clears any pause once the account is confirmed", () => {
    const started = applyStart(confirmedBatchState());
    expect(started.batch!.running).toBe(true);
    expect(started.batch!.paused).toBe(false);
  });
  it("applyPause records a reason", () => {
    const state = applyStart(confirmedBatchState());
    const paused = applyPause(state, "user");
    expect(paused.batch!.paused).toBe(true);
    expect(paused.batch!.pauseReason).toBe("user");
  });
  it("applyResume clears pause and any pending account change", () => {
    let state = applyPause(applyStart(confirmedBatchState()), "user");
    state = applyResume(state);
    expect(state.batch!.paused).toBe(false);
    expect(state.batch!.pauseReason).toBeNull();
  });
});

describe("account awareness — never reads cookies, only what's passed in from a DOM read; identity is always { memberId, displayName }", () => {
  it("the first detection records a PENDING confirmation — never the confirmed account itself", () => {
    const state = applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0);
    expect(state.batch!.account).toBeNull();
    expect(state.batch!.pendingConfirmation).toEqual({ memberId: IDENTITY_A.memberId, displayName: IDENTITY_A.displayName, detectedAt: T0 });
  });

  it("applyAccountConfirmed (the mandatory initial gate) promotes the pending identity to the confirmed account", () => {
    let state = applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0);
    state = applyAccountConfirmed(state, T1);
    expect(state.batch!.account).toEqual({ memberId: IDENTITY_A.memberId, displayName: IDENTITY_A.displayName, confirmedAt: T1 });
    expect(state.batch!.pendingConfirmation).toBeNull();
  });

  it("applyAccountConfirmed is a safe no-op when nothing is pending", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyAccountConfirmed(state, T1)).toBe(state);
  });

  it("REGRESSION: a notification-badge-only / unreliable detection (identity === null) blocks with the exact required message, and never invents a pending identity", () => {
    const state = applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), null, T0);
    expect(state.batch!.accountIdentificationError).toBe(ACCOUNT_IDENTIFICATION_ERROR);
    expect(state.batch!.account).toBeNull();
    expect(state.batch!.pendingConfirmation).toBeNull();
  });

  it("a later reliable detection clears a prior identification error", () => {
    let state = applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), null, T0);
    state = applyAccountDetected(state, IDENTITY_A, T1);
    expect(state.batch!.accountIdentificationError).toBeNull();
    expect(state.batch!.pendingConfirmation!.memberId).toBe(IDENTITY_A.memberId);
  });

  it("REGRESSION: the SAME stable memberId remains accepted even when the display name changes — never mistaken for a different account, and never pauses", () => {
    let state = applyStart(applyAccountConfirmed(applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0), T0));
    state = applyAccountDetected(state, { memberId: IDENTITY_A.memberId, displayName: "renamed_shop" }, T1);
    expect(state.batch!.paused).toBe(false);
    expect(state.batch!.pendingAccountChange).toBeNull();
    expect(state.batch!.account).toEqual({ memberId: IDENTITY_A.memberId, displayName: "renamed_shop", confirmedAt: T0 });
  });

  it("an identical re-detection (same memberId, same displayName) is a true no-op", () => {
    const state = applyStart(applyAccountConfirmed(applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0), T0));
    expect(applyAccountDetected(state, { ...IDENTITY_A }, T1)).toBe(state);
  });

  it("REGRESSION: a DIFFERENT memberId pauses the batch immediately and records both identities — never auto-resumes", () => {
    const IDENTITY_B = { memberId: "2002", displayName: "someone_else" };
    let state = applyStart(applyAccountConfirmed(applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0), T0));
    state = applyAccountDetected(state, IDENTITY_B, T1);
    expect(state.batch!.paused).toBe(true);
    expect(state.batch!.pauseReason).toBe("account_change");
    expect(state.batch!.pendingAccountChange).toEqual({
      previous: { memberId: IDENTITY_A.memberId, displayName: IDENTITY_A.displayName, confirmedAt: T0 },
      current: IDENTITY_B, detectedAt: T1,
    });
    expect(state.batch!.account).toEqual({ memberId: IDENTITY_A.memberId, displayName: IDENTITY_A.displayName, confirmedAt: T0 }); // NOT yet updated — only applyAccountChangeConfirmed does that
  });

  it("applyAccountChangeConfirmed updates the confirmed account (by memberId) and clears the pause — only after this explicit re-confirmation, never automatically", () => {
    const IDENTITY_B = { memberId: "2002", displayName: "someone_else" };
    let state = applyStart(applyAccountConfirmed(applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0), T0));
    state = applyAccountDetected(state, IDENTITY_B, T1);
    state = applyAccountChangeConfirmed(state, T1);
    expect(state.batch!.paused).toBe(false);
    expect(state.batch!.account).toEqual({ memberId: IDENTITY_B.memberId, displayName: IDENTITY_B.displayName, confirmedAt: T1 });
    expect(state.batch!.pendingAccountChange).toBeNull();
  });

  it("applyAccountChangeConfirmed is a no-op when there's no pending change", () => {
    const state = applyAccountConfirmed(applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0), T0);
    expect(applyAccountChangeConfirmed(state, T1)).toBe(state);
  });

  it("REGRESSION: a later failed re-detection (identity === null) never invalidates an already-confirmed account", () => {
    const state = applyAccountConfirmed(applyAccountDetected(applyBatchPayload(createInitialState(), payload(), T0), IDENTITY_A, T0), T0);
    const afterFailedRedetect = applyAccountDetected(state, null, T1);
    expect(afterFailedRedetect).toBe(state); // unchanged — a transient failed read is never treated as a change
    expect(afterFailedRedetect.batch!.account!.memberId).toBe(IDENTITY_A.memberId);
  });

  it("REGRESSION: a NEW batch (a fresh applyBatchPayload) always requires confirmation again, even if the previous batch's account was already confirmed", () => {
    const confirmed = confirmedBatchState();
    expect(confirmed.batch!.account!.memberId).toBe(IDENTITY_A.memberId);

    const newBatchPayload = { ...payload(), batchId: "batch-2" };
    const afterNewClaim = applyBatchPayload(confirmed, newBatchPayload, T1);
    expect(afterNewClaim.batch!.account).toBeNull();
    expect(afterNewClaim.batch!.pendingConfirmation).toBeNull();
    expect(afterNewClaim.batch!.accountIdentificationError).toBeNull();
  });

  it("REGRESSION: a NEW batch also requires fresh Vinted tab selection — vintedTabId is never carried over from the previous batch", () => {
    let state = applySelectedVintedTab(applyBatchPayload(createInitialState(), payload(), T0), 42);
    const newBatchPayload = { ...payload(), batchId: "batch-2" };
    const afterNewClaim = applyBatchPayload(state, newBatchPayload, T1);
    expect(afterNewClaim.batch!.vintedTabId).toBeNull();
  });
});

describe("resumeAfterRestart — the service-worker-suspension recovery", () => {
  it("resets an in-flight item (preparing/filling/saving) back to QUEUED", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.SAVING });
    const resumed = resumeAfterRestart(state);
    expect(resumed.batch!.items[0].status).toBe(ITEM_STATUSES.QUEUED);
  });

  it("never touches a terminal item", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemCompleted(state, "item-1", "1", T0);
    const resumed = resumeAfterRestart(state);
    expect(resumed.batch!.items[0].status).toBe(ITEM_STATUSES.COMPLETED);
  });

  it("is idempotent — a second call on already-consistent state changes nothing", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.FILLING });
    const once = resumeAfterRestart(state);
    const twice = resumeAfterRestart(once);
    expect(twice).toEqual(once);
  });

  it("is a safe no-op when there's no batch at all", () => {
    expect(resumeAfterRestart(createInitialState())).toEqual(createInitialState());
  });

  it("REGRESSION: clears vintedTabId — a Chrome tab id from a previous browser session may no longer be valid (or may now refer to an unrelated tab)", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applySelectedVintedTab(state, 999);
    const resumed = resumeAfterRestart(state);
    expect(resumed.batch!.vintedTabId).toBeNull();
  });

  it("is still idempotent once vintedTabId is already null", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applySelectedVintedTab(state, 999);
    const once = resumeAfterRestart(state);
    const twice = resumeAfterRestart(once);
    expect(twice).toBe(once);
  });
});

describe("Vinted tab selection — applySelectedVintedTab / applyVintedTabLost (arbitrary-tab-selection fix)", () => {
  it("applySelectedVintedTab persists the chosen tab id", () => {
    const state = applySelectedVintedTab(applyBatchPayload(createInitialState(), payload(), T0), 42);
    expect(state.batch!.vintedTabId).toBe(42);
  });

  it("REGRESSION: applyVintedTabLost pauses the batch with the dedicated reason, clears the stale tab id, and is detected by isVintedTabLostPause", () => {
    let state = applySelectedVintedTab(applyBatchPayload(createInitialState(), payload(), T0), 42);
    state = applyStart(applyAccountConfirmed(applyAccountDetected(state, { memberId: "1", displayName: "shopfront_uk" }, T0), T0));
    expect(isVintedTabLostPause(state)).toBe(false);

    const lost = applyVintedTabLost(state);
    expect(lost.batch!.paused).toBe(true);
    expect(lost.batch!.pauseReason).toBe("vinted_tab_lost");
    expect(lost.batch!.vintedTabId).toBeNull();
    expect(isVintedTabLostPause(lost)).toBe(true);
    expect(VINTED_TAB_LOST_MESSAGE.length).toBeGreaterThan(0);
  });

  it("isVintedTabLostPause is false for every other pause reason (e.g. a manual user pause)", () => {
    const state = applyPause(applyBatchPayload(createInitialState(), payload(), T0), "user");
    expect(isVintedTabLostPause(state)).toBe(false);
  });

  it("applyResume clears a vinted_tab_lost pause the same as any other — the next ensureVintedTab() call re-selects since vintedTabId is already null", () => {
    let state = applySelectedVintedTab(applyBatchPayload(createInitialState(), payload(), T0), 42);
    state = applyVintedTabLost(state);
    state = applyResume(state);
    expect(state.batch!.paused).toBe(false);
    expect(state.batch!.vintedTabId).toBeNull();
  });
});

describe("computeProgressSummary", () => {
  it("reports totals, completed/failed/cancelled counts, and the current in-flight item", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemCompleted(state, "item-1", "1", T0);
    state = applyItemStatus(state, "item-2", { status: ITEM_STATUSES.FILLING });
    const summary = computeProgressSummary(state);
    expect(summary).toEqual({ total: 2, completed: 1, failed: 0, cancelled: 0, remaining: 1, currentItem: state.batch!.items[1] });
  });
  it("returns all zeros/null when there's no batch", () => {
    expect(computeProgressSummary(createInitialState())).toEqual({ total: 0, completed: 0, failed: 0, cancelled: 0, remaining: 0, currentItem: null });
  });
});

describe("isBatchExpired / isTerminalStatus", () => {
  it("isBatchExpired compares against pairing.expiresAt (or batch.expiresAt as a fallback)", () => {
    const state = applyClaim(createInitialState(), { batchId: "b", batchToken: "t", expiresAt: "2026-08-05T10:00:00.000Z", claimedAt: T0 });
    expect(isBatchExpired(state, "2026-08-05T09:59:00.000Z")).toBe(false);
    expect(isBatchExpired(state, "2026-08-05T10:00:01.000Z")).toBe(true);
  });
  it("isTerminalStatus is true only for completed/failed/cancelled", () => {
    expect(isTerminalStatus(ITEM_STATUSES.COMPLETED)).toBe(true);
    expect(isTerminalStatus(ITEM_STATUSES.FAILED)).toBe(true);
    expect(isTerminalStatus(ITEM_STATUSES.CANCELLED)).toBe(true);
    expect(isTerminalStatus(ITEM_STATUSES.QUEUED)).toBe(false);
    expect(isTerminalStatus(ITEM_STATUSES.SAVING)).toBe(false);
  });
});

// ============================================================================
// Durable Save Draft confirmation (live Save Draft investigation, follow-up)
// — the pure pendingSave state machine. Every actual DECISION about what
// counts as expired/confirmed/a safe retry lives here (see this file's own
// top comment); service-worker.js is only ever the thin chrome.*
// orchestration that calls these at the right moments.
// ============================================================================

const PENDING_RECORD = {
  batchId: "batch-1", itemId: "item-1", draftId: "draft-1", vintedTabId: 7,
  expectedTitle: "Hoka Clifton 9", expectedSku: "AA1",
  clickedAt: T0, deadline: "2026-08-05T10:01:30.000Z",
};

describe("applyPendingSaveStarted — persisted BEFORE the click is ever allowed", () => {
  it("sets batch.pendingSave and marks the item SAVING with fresh progress", () => {
    const state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    expect(state.batch!.pendingSave).toEqual({ ...PENDING_RECORD, state: "awaiting_navigation_confirmation", attempts: 0 });
    const item = state.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.SAVING);
    expect(item.lastProgressAt).toBe(T0);
  });

  it("is a safe no-op when there's no batch at all", () => {
    expect(applyPendingSaveStarted(createInitialState(), PENDING_RECORD, T0)).toEqual(createInitialState());
  });
});

describe("applyPendingSaveConfirmed — the real observed Vinted success marker was found", () => {
  it("clears pendingSave and completes the item with the confirmed vintedDraftId", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyPendingSaveConfirmed(state, "9621049256", T1);
    expect(state.batch!.pendingSave).toBeNull();
    const item = state.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.COMPLETED);
    expect(item.vintedDraftId).toBe("9621049256");
    expect(item.completedAt).toBe(T1);
  });

  it("REGRESSION: duplicate/late confirmation events never duplicate completion — a SECOND call once pendingSave is already cleared is a true no-op, same reference back", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyPendingSaveConfirmed(state, "9621049256", T1);
    const again = applyPendingSaveConfirmed(state, "9621049256", T1);
    expect(again).toBe(state); // identical reference — never re-applies, never a second completion event
  });

  it("is a safe no-op when nothing is pending at all", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyPendingSaveConfirmed(state, "123", T1)).toBe(state);
  });
});

describe("applyPendingSaveCheckAttempted — a confirmation attempt found nothing yet (delayed profile rendering)", () => {
  it("bumps attempts and refreshes the item's progress clock, without touching status or pendingSave.state", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyPendingSaveCheckAttempted(state, T1);
    expect(state.batch!.pendingSave!.attempts).toBe(1);
    expect(state.batch!.pendingSave!.state).toBe("awaiting_navigation_confirmation");
    const item = state.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.SAVING); // still pending, never touched
    expect(item.lastProgressAt).toBe(T1); // refreshed — keeps the UNRELATED general watchdog from racing ahead
  });

  it("REGRESSION: repeated attempts (simulating several delayed-rendering recovery ticks) keep incrementing, never reset, never fail on their own", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyPendingSaveCheckAttempted(state, T1);
    state = applyPendingSaveCheckAttempted(state, T1);
    state = applyPendingSaveCheckAttempted(state, T1);
    expect(state.batch!.pendingSave!.attempts).toBe(3);
    expect(state.batch!.items.find((i: any) => i.itemId === "item-1")!.status).toBe(ITEM_STATUSES.SAVING);
  });

  it("is a safe no-op when nothing is pending", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyPendingSaveCheckAttempted(state, T1)).toBe(state);
  });
});

describe("isPendingSaveExpired / applyPendingSaveExpired — the deadline passed with no confirmation ever found", () => {
  it("isPendingSaveExpired compares strictly against the record's own deadline, never the general watchdog window", () => {
    const state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    expect(isPendingSaveExpired(state, "2026-08-05T10:01:29.000Z")).toBe(false);
    expect(isPendingSaveExpired(state, "2026-08-05T10:01:30.000Z")).toBe(true);
    expect(isPendingSaveExpired(state, "2026-08-05T10:05:00.000Z")).toBe(true);
  });
  it("isPendingSaveExpired is false when nothing is pending", () => {
    expect(isPendingSaveExpired(applyBatchPayload(createInitialState(), payload(), T0), T1)).toBe(false);
  });

  it("REGRESSION: a clear, specific, retryable failure — never a silent drop, never an automatic re-click", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyPendingSaveExpired(state, "2026-08-05T10:02:00.000Z");
    expect(state.batch!.pendingSave).toBeNull();
    const item = state.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.FAILED);
    expect(item.errorCode).toBe(SAVE_DRAFT_UNCONFIRMED_ERROR_CODE);
    expect(item.errorMessage).toBe(SAVE_DRAFT_UNCONFIRMED_MESSAGE);
    expect(item.errorMessage).toMatch(/check saved draft again/i);
  });

  it("is idempotent — a second call once already cleared is a true no-op", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyPendingSaveExpired(state, T1);
    expect(applyPendingSaveExpired(state, T1)).toBe(state);
  });
});

describe("applyRetryItem — REGRESSION: a confirmed/unconfirmed-save item never lets Save Draft be clicked again via the normal retry path", () => {
  it("refuses to requeue an item that failed with SAVE_DRAFT_UNCONFIRMED — a true no-op, same reference back", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemFailed(state, "item-1", SAVE_DRAFT_UNCONFIRMED_ERROR_CODE, SAVE_DRAFT_UNCONFIRMED_MESSAGE, T0);
    const retried = applyRetryItem(state, "item-1");
    expect(retried).toBe(state); // structurally refused
    expect(retried.batch!.items[0].status).toBe(ITEM_STATUSES.FAILED); // never requeued
  });

  it("every OTHER failure reason is still retried normally — this refusal is specific to SAVE_DRAFT_UNCONFIRMED alone", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemFailed(state, "item-1", "SET_PRICE", "some other failure", T0);
    const retried = applyRetryItem(state, "item-1");
    expect(retried.batch!.items[0].status).toBe(ITEM_STATUSES.QUEUED);
    expect(retried.batch!.items[0].errorCode).toBeNull();
  });
});

describe("resumeAfterRestart — REGRESSION: a live pendingSave is never silently requeued (would risk a duplicate Save Draft click), and is never immediately failed either (restart-recovery gap fix)", () => {
  // PENDING_RECORD's own deadline is "2026-08-05T10:01:30.000Z"; T1 is
  // "2026-08-05T10:01:00.000Z" — 30s BEFORE that deadline.
  it("REGRESSION: a SAVING item with a pendingSave that is NOT yet past its deadline is PRESERVED across a restart — never immediately failed, never requeued", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    const resumed = resumeAfterRestart(state, T1);

    expect(resumed.batch!.pendingSave).not.toBeNull();
    expect(resumed.batch!.pendingSave!.itemId).toBe("item-1");
    expect(resumed.batch!.pendingSave!.deadline).toBe(PENDING_RECORD.deadline); // the SAME deadline — restart never grants extra time
    const item = resumed.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.SAVING); // never reset to QUEUED (would risk a duplicate click) and never FAILED (restart isn't an automatic hard failure)
  });

  it("REGRESSION: the preserved pendingSave's OWN vintedTabId is cleared (the old id can never be trusted after a restart) — the service worker must reacquire one before it can check again", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    const resumed = resumeAfterRestart(state, T1);
    expect(resumed.batch!.pendingSave!.vintedTabId).toBeNull();
  });

  it("REGRESSION: a pendingSave that IS already past its own deadline by restart time still expires normally — the ordinary SAVE_DRAFT_UNCONFIRMED failure, not a special-cased 'restart' failure", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    const AFTER_DEADLINE = "2026-08-05T10:02:00.000Z"; // 30s past PENDING_RECORD's own deadline
    const resumed = resumeAfterRestart(state, AFTER_DEADLINE);

    expect(resumed.batch!.pendingSave).toBeNull();
    const item = resumed.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.FAILED);
    expect(item.errorCode).toBe(SAVE_DRAFT_UNCONFIRMED_ERROR_CODE);
  });

  it("without a nowIso argument at all, a live pendingSave is conservatively PRESERVED, never guessed as expired", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    const resumed = resumeAfterRestart(state, undefined);
    expect(resumed.batch!.pendingSave).not.toBeNull();
    expect(resumed.batch!.items.find((i: any) => i.itemId === "item-1")!.status).toBe(ITEM_STATUSES.SAVING);
  });

  it("REGRESSION: browser restart while confirmation is pending also clears the BATCH's own vintedTabId regardless of whether the pending save is preserved or expired — the old tab id can never be trusted either way", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applySelectedVintedTab(state, PENDING_RECORD.vintedTabId);
    const resumed = resumeAfterRestart(state, T1); // preserved branch
    expect(resumed.batch!.vintedTabId).toBeNull();
  });

  it("a SECOND, different item that is genuinely just FILLING (no pendingSave, no click risk) still resets to QUEUED as before — the special-case is narrowly scoped to the item a live pendingSave actually belongs to", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = applyItemStatus(state, "item-2", { status: ITEM_STATUSES.FILLING }, T0);
    const resumed = resumeAfterRestart(state, T1);
    expect(resumed.batch!.items.find((i: any) => i.itemId === "item-2")!.status).toBe(ITEM_STATUSES.QUEUED);
  });

  it("REGRESSION: existing behaviour for a plain in-flight item (no pendingSave at all) is completely unchanged — still resets to QUEUED", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyItemStatus(state, "item-1", { status: ITEM_STATUSES.SAVING }, T0);
    const resumed = resumeAfterRestart(state, T1);
    expect(resumed.batch!.items[0].status).toBe(ITEM_STATUSES.QUEUED);
  });
});

describe("applyPendingSaveTabReacquired — restart-recovery gap fix: records a freshly reacquired tab id, refreshes progress", () => {
  it("sets pendingSave.vintedTabId and refreshes the item's own progress clock", () => {
    let state = applyPendingSaveStarted(applyBatchPayload(createInitialState(), payload(), T0), PENDING_RECORD, T0);
    state = resumeAfterRestart(state, T1); // clears the old vintedTabId, preserves the record
    expect(state.batch!.pendingSave!.vintedTabId).toBeNull();

    const reacquired = applyPendingSaveTabReacquired(state, 42, T1);
    expect(reacquired.batch!.pendingSave!.vintedTabId).toBe(42);
    expect(reacquired.batch!.items.find((i: any) => i.itemId === "item-1")!.lastProgressAt).toBe(T1);
  });

  it("is a safe no-op when nothing is pending", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyPendingSaveTabReacquired(state, 42, T1)).toBe(state);
  });
});

describe("Manual browser reload (native browser reload-confirmation bug) — applyManualReloadNeeded / isManualReloadPause / applyManualReloadAttempt / applyManualReloadTabReacquired / applyManualReloadResolved", () => {
  it("REQUIREMENT: marks the item WAITING_FOR_MANUAL_RELOAD (never FAILED) and pauses the batch with the dedicated reason", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);

    const item = state.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.WAITING_FOR_MANUAL_RELOAD);
    expect(item.status).not.toBe(ITEM_STATUSES.FAILED);
    expect(state.batch!.paused).toBe(true);
    expect(isManualReloadPause(state)).toBe(true);
    expect(state.batch!.manualReload).toEqual({ itemId: "item-1", tabId: 7, startedAt: T0, attempts: 1, lastAttemptAt: T0 });
  });

  it("REQUIREMENT: exact warning text is exported as the single source of truth for the side panel banner and Live activity entry", () => {
    expect(MANUAL_RELOAD_WARNING_MESSAGE).toBe("Browser needs manual reload — click Reload in the Vinted confirmation box to continue.");
  });

  it("a safe no-op when there is no active batch", () => {
    expect(applyManualReloadNeeded(createInitialState(), { itemId: "item-1", tabId: 7 }, T0)).toEqual(createInitialState());
  });

  it("REGRESSION: calling it again for the SAME item (e.g. a later ensureCleanCreateForm attempt) bumps attempts/lastAttemptAt on the existing record instead of creating a second one or re-pausing what's already paused", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 9 }, T1);

    expect(state.batch!.manualReload).toEqual({ itemId: "item-1", tabId: 9, startedAt: T0, attempts: 2, lastAttemptAt: T1 });
    expect(state.batch!.pauseReason).toBe("manual_reload_required");
  });

  it("REGRESSION: never begins another item while waiting — computeProgressSummary reports the waiting item as currentItem, exactly like an in-flight one", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    const summary = computeProgressSummary(state);
    expect(summary.currentItem?.itemId).toBe("item-1");
  });

  it("REGRESSION: never treated as stalled by the generic watchdog and never reset to QUEUED by a blanket in-flight restart-reset — findStalledItem/resumeAfterRestart both use a NARROWER in-flight set that excludes this status", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    const resumed = resumeAfterRestart(state, T1);
    const item = resumed.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.WAITING_FOR_MANUAL_RELOAD); // never reset to QUEUED, never FAILED
    expect(resumed.batch!.paused).toBe(true); // the pause (and its warning) survive a restart untouched
  });

  it("REGRESSION (restart-recovery gap): resumeAfterRestart clears the manualReload record's OWN stale tabId (never trusted after a restart) but preserves everything else about the wait", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    const resumed = resumeAfterRestart(state, T1);
    expect(resumed.batch!.manualReload!.tabId).toBeNull();
    expect(resumed.batch!.manualReload!.itemId).toBe("item-1");
    expect(resumed.batch!.manualReload!.attempts).toBe(1);
  });

  it("applyManualReloadAttempt bumps attempts/lastAttemptAt only — never touches item status or the pause", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    state = applyManualReloadAttempt(state, T1);
    expect(state.batch!.manualReload).toEqual({ itemId: "item-1", tabId: 7, startedAt: T0, attempts: 2, lastAttemptAt: T1 });
    expect(state.batch!.items.find((i: any) => i.itemId === "item-1")!.status).toBe(ITEM_STATUSES.WAITING_FOR_MANUAL_RELOAD);
  });

  it("applyManualReloadAttempt is a safe no-op when nothing is waiting", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyManualReloadAttempt(state, T1)).toBe(state);
  });

  it("applyManualReloadTabReacquired records a freshly reacquired tab id and refreshes the item's progress clock (mirrors applyPendingSaveTabReacquired)", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    state = resumeAfterRestart(state, T1); // clears the old tabId
    expect(state.batch!.manualReload!.tabId).toBeNull();

    const reacquired = applyManualReloadTabReacquired(state, 42, T1);
    expect(reacquired.batch!.manualReload!.tabId).toBe(42);
    expect(reacquired.batch!.items.find((i: any) => i.itemId === "item-1")!.lastProgressAt).toBe(T1);
  });

  it("applyManualReloadTabReacquired is a safe no-op when nothing is waiting", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyManualReloadTabReacquired(state, 42, T1)).toBe(state);
  });

  it("REQUIREMENT: applyManualReloadResolved (a freshly-observed clean page) clears the record, resumes the batch, and resets the waiting item back to QUEUED — no Retry needed", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    const resolved = applyManualReloadResolved(state, T1);

    expect(resolved.batch!.manualReload).toBeNull();
    expect(resolved.batch!.paused).toBe(false);
    expect(resolved.batch!.pauseReason).toBeNull();
    expect(isManualReloadPause(resolved)).toBe(false);
    const item = resolved.batch!.items.find((i: any) => i.itemId === "item-1")!;
    expect(item.status).toBe(ITEM_STATUSES.QUEUED);
  });

  it("REGRESSION: applyManualReloadResolved never steals a resume from a genuinely different, unrelated pause active at the same moment", () => {
    let state = applyBatchPayload(createInitialState(), payload(), T0);
    state = applyManualReloadNeeded(state, { itemId: "item-1", tabId: 7 }, T0);
    // Simulate an unrelated pause reason somehow becoming active (e.g. a
    // vinted-tab-lost pause layered on top) — applyManualReloadResolved
    // must only ever resume the pause it itself owns.
    state = { ...state, batch: { ...state.batch!, pauseReason: "vinted_tab_lost" } };
    const resolved = applyManualReloadResolved(state, T1);
    expect(resolved.batch!.paused).toBe(true); // NOT resumed — a different pause is still active
    expect(resolved.batch!.pauseReason).toBe("vinted_tab_lost");
    expect(resolved.batch!.manualReload).toBeNull(); // the record itself is still cleared
    expect(resolved.batch!.items.find((i: any) => i.itemId === "item-1")!.status).toBe(ITEM_STATUSES.QUEUED);
  });

  it("applyManualReloadResolved is a safe no-op when nothing is waiting (idempotent against a second/late resolution)", () => {
    const state = applyBatchPayload(createInitialState(), payload(), T0);
    expect(applyManualReloadResolved(state, T1)).toBe(state);
  });

  it("isManualReloadPause is false for an ordinary pause (e.g. 'user') and for no pause at all", () => {
    const noBatchPause = applyBatchPayload(createInitialState(), payload(), T0);
    expect(isManualReloadPause(noBatchPause)).toBe(false);
    const userPaused = applyPause(noBatchPause, "user");
    expect(isManualReloadPause(userPaused)).toBe(false);
  });
});
