"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createVaultItem, loadVaultItems, uploadVaultFiles, type VaultItem, type VaultKind } from "@/lib/vault-storage";
import { VaultIcon } from "./VaultIcons";
import styles from "./vault.module.css";

const kinds: { kind: VaultKind; label: string; description: string }[] = [
  { kind: "note", label: "Note", description: "Write anything" }, { kind: "link", label: "Link", description: "Save a website" },
  { kind: "file", label: "File", description: "Upload CSV, Excel, PDF or document" }, { kind: "guide", label: "Guide", description: "Create a reusable guide" },
  { kind: "release", label: "Release info", description: "Track an upcoming release" }, { kind: "private", label: "Private note", description: "Keep sensitive information locked" },
];
const filters = ["All", "Notes", "Links", "Files", "Guides", "Private"];
const kindLabel: Record<VaultKind, string> = { note: "Note", link: "Link", file: "File", guide: "Guide", release: "Release info", private: "Private" };
const formatDate = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));
const formatSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export default function VaultWorkspace() {
  const [items, setItems] = useState<VaultItem[]>([]), [ready, setReady] = useState(false), [loadError, setLoadError] = useState(""), [query, setQuery] = useState(""), [filter, setFilter] = useState("All"), [view, setView] = useState<"cards" | "list">("cards"), [modal, setModal] = useState(false), [step, setStep] = useState<1|2|3>(1), [kind, setKind] = useState<VaultKind | null>(null), [saved, setSaved] = useState<VaultItem | null>(null);
  const [title, setTitle] = useState(""), [folder, setFolder] = useState(""), [tags, setTags] = useState(""), [content, setContent] = useState(""), [url, setUrl] = useState(""), [releaseDate, setReleaseDate] = useState(""), [pinned, setPinned] = useState(true), [isPrivate, setPrivate] = useState(false), [files, setFiles] = useState<File[]>([]), [saving, setSaving] = useState(false);
  useEffect(() => { loadVaultItems().then(setItems).catch(error=>setLoadError(error instanceof Error?error.message:"Could not load Vault.")).finally(()=>setReady(true)); }, []);
  const visible = useMemo(() => items.filter(item => { const f = filter === "All" || (filter === "Notes" && item.kind === "note") || (filter === "Links" && item.kind === "link") || (filter === "Files" && item.kind === "file") || (filter === "Guides" && item.kind === "guide") || (filter === "Private" && item.private); const q = `${item.title} ${item.content} ${item.tags.join(" ")}`.toLowerCase(); return f && q.includes(query.toLowerCase()); }).sort((a,b) => Number(b.pinned)-Number(a.pinned) || b.updatedAt.localeCompare(a.updatedAt)), [items, filter, query]);
  const counts = { all: items.length, guide: items.filter(x=>x.kind==="guide").length, release: items.filter(x=>x.kind==="release").length, file: items.filter(x=>x.kind==="file").length, link: items.filter(x=>x.kind==="link").length, private: items.filter(x=>x.private).length };
  function reset() { setStep(1); setKind(null); setSaved(null); setTitle(""); setFolder(""); setTags(""); setContent(""); setUrl(""); setReleaseDate(""); setPinned(true); setPrivate(false); setFiles([]); }
  function choose(next: VaultKind) { setKind(next); setFolder(next === "guide" ? "Guides" : next === "release" ? "Release info" : next === "private" ? "Private" : next === "link" ? "Links" : next === "file" ? "Files" : "Notes"); setPrivate(next === "private"); setStep(2); }
  async function submit() { if (!kind || !title.trim()) return; setSaving(true); setLoadError(""); try { let item=await createVaultItem({kind,title:title.trim(),folder,tags:tags.split(",").map(x=>x.trim()).filter(Boolean),content,url:url||undefined,releaseDate:releaseDate||undefined,pinned,private:isPrivate}); if(files.length)item={...item,attachments:await uploadVaultFiles(item.id,files)};setItems(current=>[item,...current]);setSaved(item);setStep(3); } catch(error){setLoadError(error instanceof Error?error.message:"Could not save Vault item.")} finally {setSaving(false)} }
  return <section className={`page-shell ${styles.shell}`}>
    <header className={styles.header}><div><h1>Vault</h1><p>Everything worth keeping, all in one place.</p></div><button className="button" onClick={()=>{reset();setModal(true)}}><span className="button-plus">+</span>Add to Vault</button></header>
    <div className={styles.toolbar}><label className={styles.search}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your vault..." /></label><div className={styles.filters}>{filters.map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?styles.active:""}>{x}</button>)}</div><div className={styles.view}><button onClick={()=>setView("cards")} className={view==="cards"?styles.active:""}>Cards</button><button onClick={()=>setView("list")} className={view==="list"?styles.active:""}>List</button></div></div>
    <div className={styles.stats}>{([{kind:"all",label:"All items",n:counts.all},{kind:"guide",label:"Guides",n:counts.guide},{kind:"release",label:"Release info",n:counts.release},{kind:"file",label:"Files",n:counts.file},{kind:"link",label:"Links",n:counts.link},{kind:"private",label:"Private",n:counts.private}] as const).map(x=><div className={`${styles.stat} ${styles[x.kind]}`} key={x.label}><span className={styles.icon}><VaultIcon kind={x.kind}/></span><div><small>{x.label}</small><strong>{x.n}</strong></div></div>)}</div>
    {loadError&&<div className={styles.error}>{loadError}</div>}{!ready ? <div className={styles.empty}>Loading your vault…</div> : visible.length===0 ? <div className={styles.empty}><VaultIcon kind="all"/><h2>Your Vault is empty</h2><p>Add your first note, link, file, guide or release.</p></div> : view === "cards" ? <div className={styles.cards}>{visible.map(item=><VaultCard key={item.id} item={item}/>)}</div> : <VaultTable items={visible}/>}
    {modal && <div className={styles.overlay} onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><div className={styles.modal} role="dialog" aria-modal="true"><button className={styles.close} onClick={()=>setModal(false)} aria-label="Close">×</button>{step===1&&<><div className={styles.modalHead}><h2>Add to Vault</h2><p>What would you like to save?</p></div><div className={styles.kindGrid}>{kinds.map(x=><button key={x.kind} onClick={()=>choose(x.kind)} className={styles.kindChoice}><span className={`${styles.icon} ${styles[x.kind]}`}><VaultIcon kind={x.kind}/></span><strong>{x.label}</strong><small>{x.description}</small></button>)}</div><div className={styles.modalActions}><button className="button-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="button" disabled>Continue</button></div></>}{step===2&&kind&&<><StepBar step={2}/><div className={styles.modalHead}><h2>Add {kindLabel[kind].toLowerCase()}</h2></div><div className={styles.form}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus placeholder="Give this item a clear title" /></label><div className={styles.formRow}><label>Folder<input value={folder} onChange={e=>setFolder(e.target.value)} /></label><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Selling, Vinted" /></label></div>{kind==="link"&&<label>Website URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://" /></label>}{kind==="release"&&<label>Release date<input type="date" value={releaseDate} onChange={e=>setReleaseDate(e.target.value)} /></label>}<label>Content<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Write or paste the information you want to keep..." /></label><label className={styles.drop}>Drop files here or <span>browse</span><input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small>{files.length ? files.map(x=>x.name).join(", ") : "CSV, Excel, PDF or document"}</small></label><Switch label="Pin this item" checked={pinned} set={setPinned}/><Switch label="Keep private" checked={isPrivate} set={setPrivate}/></div><div className={styles.modalActions}><button className="button-secondary" onClick={()=>setStep(1)}>Back</button><button className="button" disabled={!title.trim()||saving} onClick={submit}>{saving?"Saving…":"Save to Vault"}</button></div></>}{step===3&&saved&&<><StepBar step={3}/><div className={styles.success}><span>✓</span><h2>Saved to Vault</h2><p>{saved.title} is ready.</p><VaultCard item={saved}/><div><Link className="button" href={`/vault/${saved.id}`}>View item</Link><button className="button-secondary" onClick={reset}>Add another</button></div></div></>}</div></div>}
  </section>;
}
function VaultCard({item}:{item:VaultItem}) { return <Link href={`/vault/${item.id}`} className={`${styles.card} ${styles[item.kind]}`}>{item.pinned&&<span className={styles.pin}>⌖ Pinned</span>}<span className={`${styles.icon} ${styles[item.kind]}`}><VaultIcon kind={item.kind}/></span><div className={styles.cardCopy}><strong>{item.title}</strong><div className={styles.tags}>{item.tags.map(x=><span key={x}>{x}</span>)}{item.private&&<span>Private</span>}</div><p>{item.kind==="private"?"••••••••••••••••":item.url||item.content.replace(/[#•☑>]/g,"").slice(0,90)}</p><small>Updated {formatDate(item.updatedAt)}{item.attachments[0]?` · ${formatSize(item.attachments[0].size)}`:""}</small></div><b className={styles.more}>•••</b></Link> }
function VaultTable({items}:{items:VaultItem[]}) { return <div className={styles.table}><div className={styles.tableHead}>List view <span>{items.length} items</span></div><div className={styles.tableScroll}><table><thead><tr><th>Name</th><th>Type</th><th>Tags</th><th>Updated</th><th>Size</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><Link href={`/vault/${x.id}`}><VaultIcon kind={x.kind}/>{x.title}</Link></td><td>{kindLabel[x.kind]}</td><td><span className={styles.tag}>{x.tags.join(", ")||"—"}</span></td><td>{formatDate(x.updatedAt)}</td><td>{x.attachments[0]?formatSize(x.attachments[0].size):"—"}</td><td>•••</td></tr>)}</tbody></table></div></div> }
function StepBar({step}:{step:number}) { return <div className={styles.steps}><span className={step===1?styles.active:""}>① Type</span><span className={step===2?styles.active:""}>② Details</span><span className={step===3?styles.active:""}>③ Done</span></div> }
function Switch({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}) { return <label className={styles.switchRow}><span><strong>{label}</strong><small>{label.startsWith("Pin")?"Keep this item at the top of your vault.":"Only you can view this item."}</small></span><button type="button" role="switch" aria-checked={checked} className={checked?styles.switchOn:""} onClick={()=>set(!checked)}><i/></button></label> }
