import "server-only";
import type { EmailSearch } from "@/lib/validation/email";
import { signEmailId, verifyEmailId } from "@/lib/yahoo/tokens";
import { gmailAccessToken } from "./oauth";
import { sanitizeEmailHtml, excerpt } from "@/lib/yahoo/sanitize";
import { classifyQueryIntent, type EmailType } from "@/lib/email/classify";
import { matchesLifecycleEvidence } from "@/lib/email/lifecycle-evidence";

type GmailMessage = { id:string; threadId:string; labelIds?:string[]; snippet?:string; internalDate?:string; payload?:GmailPart };
type GmailPart = { mimeType?:string; filename?:string; headers?:Array<{name:string;value:string}>; body?:{data?:string;size?:number}; parts?:GmailPart[] };
function header(message:GmailMessage,name:string){ return message.payload?.headers?.find(item=>item.name.toLowerCase()===name.toLowerCase())?.value || ""; }
function decode(value?:string){ return value ? Buffer.from(value.replace(/-/g,"+").replace(/_/g,"/"),"base64").toString("utf8") : ""; }
function bodies(part?:GmailPart, out:{text:string[];html:string[];attachments:Array<{filename:string;contentType:string;size:number}>}={text:[],html:[],attachments:[]}) { if(!part)return out; const data=decode(part.body?.data); if(part.mimeType==="text/plain"&&data)out.text.push(data); if(part.mimeType==="text/html"&&data)out.html.push(data); if(part.filename)out.attachments.push({filename:part.filename,contentType:part.mimeType||"application/octet-stream",size:part.body?.size||0}); part.parts?.forEach(child=>bodies(child,out)); return out; }
async function api(ownerId:string,path:string,init?:RequestInit){ const {accessToken}=await gmailAccessToken(ownerId); const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/${path}`,{...init,headers:{...Object.fromEntries(new Headers(init?.headers)),Authorization:`Bearer ${accessToken}`},cache:"no-store"}); if(!response.ok)throw new Error("Gmail API request failed."); return response; }
function query(criteria:EmailSearch){ const parts:string[]=[]; if(criteria.sender)parts.push(`from:(${criteria.sender})`); if(criteria.recipient)parts.push(`to:(${criteria.recipient})`); if(criteria.subject)parts.push(`subject:(${criteria.subject})`); if(criteria.exactPhrase)parts.push(`"${criteria.exactPhrase.replace(/"/g,"")}"`); if(criteria.startDate)parts.push(`after:${criteria.startDate.replace(/-/g,"/")}`); if(criteria.endDate){const next=new Date(`${criteria.endDate}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+1);parts.push(`before:${next.toISOString().slice(0,10).replace(/-/g,"/")}`);} if(criteria.readStatus==="unread")parts.push("is:unread");if(criteria.readStatus==="read")parts.push("is:read");if(criteria.hasAttachments)parts.push("has:attachment");if(criteria.attachmentFilename)parts.push(`filename:${criteria.attachmentFilename}`); parts.push(...criteria.terms); return parts.join(" "); }
async function getMessage(ownerId:string,id:string){ return (await api(ownerId,`messages/${encodeURIComponent(id)}?format=full`)).json() as Promise<GmailMessage>; }
function toResult(message:GmailMessage,id:string){ const content=bodies(message.payload); const text=content.text.join("\n")||content.html.join("\n")||message.snippet||""; return {id,sender:header(message,"From")||"Unknown sender",recipient:header(message,"To"),subject:header(message,"Subject")||"(No subject)",date:message.internalDate?new Date(Number(message.internalDate)).toISOString():null,folder:"Gmail",excerpt:excerpt(text,2000),whyMatched:"Matched the connected Gmail account.",hasAttachments:content.attachments.length>0,attachmentFilenames:content.attachments.map(item=>item.filename).slice(0,10),unread:message.labelIds?.includes("UNREAD")||false}; }
export async function searchGmail(ownerId:string,criteria:EmailSearch){ const params=new URLSearchParams({q:query(criteria),maxResults:String(criteria.maxResults)}); if(criteria.cursor)params.set("pageToken",criteria.cursor); const list=await (await api(ownerId,`messages?${params}`)).json() as {messages?:Array<{id:string}>;nextPageToken?:string}; const messages=await Promise.all((list.messages||[]).map(item=>getMessage(ownerId,item.id))); return {results:await Promise.all(messages.map(async m=>toResult(m,await signEmailId({provider:"gmail",messageId:m.id})))),nextCursor:list.nextPageToken||null}; }
export async function getGmailEmail(ownerId:string,token:string){ const payload=await verifyEmailId(token); if(payload.provider!=="gmail")throw new Error("Email provider mismatch."); const message=await getMessage(ownerId,payload.messageId); const content=bodies(message.payload); const html=content.html.join("\n")||content.text.map(value=>`<pre>${value}</pre>`).join("\n"); return {...toResult(message,token),messageId:`gmail:${message.id}`,html:sanitizeEmailHtml(html),text:excerpt(content.text.join("\n")||content.html.join("\n"),20000),attachments:content.attachments.slice(0,20)}; }
export async function getGmailEmails(ownerId:string,ids:string[]){ const values=await Promise.all(ids.map(async id=>{try{return await getGmailEmail(ownerId,id);}catch{return null;}}));return values.filter((value):value is NonNullable<typeof value>=>Boolean(value)); }
export async function countGmail(ownerId:string,criteria:EmailSearch,expectedType?:EmailType){ let pageToken:string|undefined;let count=0;const expected=expectedType??classifyQueryIntent(criteria.terms);do{const params=new URLSearchParams({q:query({...criteria,maxResults:25}),maxResults:"500"});if(pageToken)params.set("pageToken",pageToken);const list=await(await api(ownerId,`messages?${params}`)).json() as {messages?:Array<{id:string}>;nextPageToken?:string};if(expected==="other")count+=(list.messages||[]).length;else{for(const item of list.messages||[]){const message=await getMessage(ownerId,item.id);const content=bodies(message.payload);if(matchesLifecycleEvidence(expected,`${header(message,"Subject")} ${content.text.join(" ")} ${content.html.join(" ")}`))count++;}}pageToken=list.nextPageToken;}while(pageToken);return{count,foldersSearched:1};}
export async function scanGmailMetadata(ownerId:string,startDate:string,endDate:string,limit=5000,sender?:string){const criteria:EmailSearch={terms:[],sender,startDate,endDate,readStatus:"any",maxResults:25};let cursor:string|undefined;const rows:Array<{id:string;sender_name:string|null;sender_address:string|null;subject:string;email_date:string;unread:boolean;has_attachments:boolean}>=[];do{const found=await searchGmail(ownerId,{...criteria,cursor});for(const result of found.results){rows.push({id:result.id,sender_name:result.sender,sender_address:result.sender,subject:result.subject,email_date:result.date||new Date(0).toISOString(),unread:result.unread,has_attachments:result.hasAttachments});if(rows.length>=limit)return{rows,truncated:true};}cursor=found.nextCursor||undefined;}while(cursor);return{rows,truncated:false};}
