import { NextResponse } from "next/server"; import { z } from "zod"; import { requireOwner } from "@/lib/auth/server"; import { safeApiError } from "@/lib/auth/api"; import { conditions, purchaseInputSchema } from "@/lib/validation/purchase"; import { supabaseRequest } from "@/lib/supabase"; import { audit, enforceRateLimit } from "@/lib/security/activity";
const editSchema = z.object({ candidateId: z.string().uuid(), purchased_from: z.string().trim().min(1).max(100), sku: z.string().trim().max(100), item_description: z.string().trim().min(1), seller_name: z.string().trim().max(200), item_size: z.string().trim().min(1), item_condition: z.enum(conditions), price_purchased: z.coerce.number().nonnegative(), order_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), arrived: z.boolean().nullable().default(null) }).strict();
const importSchema = z.object({ confirmed: z.literal(true), records: z.array(editSchema).min(1).max(100) }).strict();
export async function POST(request: Request) { try { const user = await requireOwner(); await enforceRateLimit(user.id, "purchase_email_import", 5, 300); const { records } = importSchema.parse(await request.json()); const ids = records.map(x => x.candidateId); const candidates = await (await supabaseRequest(`vinted_import_candidates?owner_id=eq.${user.id}&id=in.(${ids.join(",")})&select=id,subject,imported_purchase_id,order_reference,fingerprint,purchased_from,candidate_type`)).json() as { id: string; subject: string; imported_purchase_id: string | null; order_reference: string | null; fingerprint: string; purchased_from: string | null; candidate_type: string }[];
    const sellerNotice = (subject: string) => /(?:you(?:'|’)?ve sold an item|your item (?:has )?sold|item sold on vinted)/i.test(subject);
    const available = new Map(candidates.filter(x => !x.imported_purchase_id && !sellerNotice(x.subject)).map(x => [x.id, x])); let duplicates = records.filter(x => !available.has(x.candidateId)).length; let inserted = 0; let total = 0;
    for (const record of records) { const candidate = available.get(record.candidateId); if (!candidate) continue; const purchase = purchaseInputSchema.parse({ order_date: record.order_date, purchased_from: record.purchased_from || candidate.purchased_from || (candidate.candidate_type === "vinted" ? "Vinted" : "Unknown retailer"), seller_name: record.seller_name || null, sku: record.sku, item_description: record.item_description, item_size: record.item_size, quantity: 1, item_condition: record.item_condition, price_purchased: record.price_purchased, arrived: record.arrived });
      try { const response = await supabaseRequest("purchases", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ ...purchase, vinted_candidate_id: record.candidateId, vinted_order_reference: candidate.order_reference, vinted_fingerprint: candidate.fingerprint }) }); const purchaseId = ((await response.json()) as { id: string }[])[0]?.id; if (!purchaseId) continue; await supabaseRequest(`vinted_import_candidates?id=eq.${record.candidateId}`, { method: "PATCH", body: JSON.stringify({ import_status: "imported", imported_purchase_id: purchaseId, imported_at: new Date().toISOString() }) }); inserted++; total += purchase.price_purchased; } catch { duplicates++; }
    }
    await audit(user.id, "import_confirmed", { requested: records.length, inserted, duplicates, total: total.toFixed(2) }); return NextResponse.json({ inserted, duplicates, total: total.toFixed(2), currency: "GBP" }, { status: inserted ? 201 : 200 });
  } catch (error) { return safeApiError(error, "Purchase import could not be completed safely."); } }
