"use client";
import { useEffect, useState } from "react";

type YahooStatus = { configured: boolean; maskedAddress: string | null; connected?: boolean; testedAt?: string; lastSuccessful?: string | null };
type GmailStatus = { configured: boolean; accounts: Array<{ id:string; emailAddress:string; status:string; connectedAt:string }> };
type IndexStatus = {
  count: number; lastSyncedAt: string | null;
  currentlyIndexing: { rangeStart: string; rangeEnd: string; startedAt: string } | null;
  inProgress: { rangeStart: string; rangeEnd: string; indexedSoFar: number; lastPassAt: string } | null;
  lastFailure: { rangeStart: string; rangeEnd: string; occurredAt: string; reason: string | null } | null;
};

export default function SettingsPage() {
  const today = new Date().toISOString().slice(0, 10); const ago = new Date(Date.now() - 14 * 86400000).toISOString().slice(0, 10);
  const [theme, setTheme] = useState<"light" | "dark">("light"); const [yahoo, setYahoo] = useState<YahooStatus | null>(null); const [gmail,setGmail]=useState<GmailStatus|null>(null); const [testing, setTesting] = useState(false); const [connectionError, setConnectionError] = useState("");
  const [index, setIndex] = useState<IndexStatus | null>(null); const [startDate, setStartDate] = useState(ago); const [endDate, setEndDate] = useState(today); const [syncing, setSyncing] = useState(false); const [indexMessage, setIndexMessage] = useState("");
  async function loadIndex() { const response = await fetch("/api/yahoo/index"); if (response.ok) setIndex(await response.json()); }
  useEffect(() => { setTheme(document.documentElement.classList.contains("dark") ? "dark" : "light"); fetch("/api/yahoo/connection").then(async response => response.ok && setYahoo(await response.json())); fetch("/api/gmail/accounts").then(async response=>response.ok&&setGmail(await response.json())); loadIndex(); }, []);
  async function disconnectGmail(id:string){if(!window.confirm("Disconnect this Gmail account?"))return;const response=await fetch("/api/gmail/accounts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(response.ok)setGmail(current=>current?{...current,accounts:current.accounts.filter(account=>account.id!==id)}:current);}
  function chooseTheme(next: "light" | "dark") { setTheme(next); document.documentElement.classList.toggle("dark", next === "dark"); localStorage.setItem("purchase-tracker-theme", next); window.dispatchEvent(new Event("purchase-theme-change")); }
  async function testConnection() { setTesting(true); setConnectionError(""); const response = await fetch("/api/yahoo/connection", { method: "POST" }); const body = await response.json(); if (response.ok) setYahoo(current => ({ configured: true, maskedAddress: body.maskedAddress || current?.maskedAddress || null, connected: true, testedAt: body.testedAt })); else setConnectionError(body.error || "Connection test failed."); setTesting(false); }
  function describePass(pass: { status: string; rangeStart?: string; rangeEnd?: string; indexed?: number; note?: string } | null, label: string) {
    if (!pass || pass.status === "already_covered") return "";
    if (pass.status === "completed") return `${label}: indexed ${pass.indexed} metadata records for ${pass.rangeStart} to ${pass.rangeEnd}. `;
    if (pass.status === "partial") return `${label}: ${pass.note} `;
    return "";
  }
  async function syncIndex() { setSyncing(true); setIndexMessage(""); const response = await fetch("/api/yahoo/index", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startDate, endDate }) }); const body = await response.json(); setIndexMessage(response.ok ? (describePass(body.historical, "Historical") + describePass(body.today, "Today")).trim() || "This range is already fully indexed." : body.error || "Metadata sync failed."); if (response.ok) await loadIndex(); setSyncing(false); }
  async function clearIndex() { if (!window.confirm("Clear the private email metadata index? This does not delete anything from Yahoo and it can be rebuilt.")) return; const response = await fetch("/api/yahoo/index", { method: "DELETE" }); setIndexMessage(response.ok ? "Metadata index cleared. Yahoo Mail was not changed." : "The index could not be cleared."); if (response.ok) await loadIndex(); }
  return <section className="page-shell page-narrow"><header className="page-header"><div className="title-row"><h1>Settings</h1></div></header><div className="settings-panel">
    <div className="settings-section"><div className="settings-copy"><h2>Appearance</h2><p>Choose how Purchase Tracker looks on this device.</p></div><div className="theme-options"><button type="button" className={theme === "light" ? "theme-option theme-option-active" : "theme-option"} onClick={() => chooseTheme("light")}><span className="theme-preview theme-preview-light"><i /><i /></span><strong>Light</strong></button><button type="button" className={theme === "dark" ? "theme-option theme-option-active" : "theme-option"} onClick={() => chooseTheme("dark")}><span className="theme-preview theme-preview-dark"><i /><i /></span><strong>Dark</strong></button></div></div>
    <div className="settings-row"><div><h2>Workspace</h2><p>Personal workspace · Supabase database</p></div><span className="status-badge"><i />Protected</span></div>
    <div className="settings-section yahoo-settings"><div className="settings-copy"><h2>Yahoo Mail</h2><p>Read-only IMAP access is configured only through server environment variables.</p><ol><li>Enable Yahoo two-step verification.</li><li>Create a Yahoo app password.</li><li>Set YAHOO_EMAIL and YAHOO_APP_PASSWORD locally and in Vercel.</li></ol></div><div className="yahoo-status"><span className={yahoo?.configured ? "status-badge" : "status-badge status-off"}><i />{yahoo?.configured ? "Configured" : "Not configured"}</span><strong>{yahoo?.maskedAddress || "No address configured"}</strong>{yahoo?.connected && <small>Connected · tested {yahoo.testedAt ? new Date(yahoo.testedAt).toLocaleString() : "just now"}</small>}{!yahoo?.connected && yahoo?.lastSuccessful && <small>Last successful connection or sync: {new Date(yahoo.lastSuccessful).toLocaleString()}</small>}{connectionError && <small className="purchase-form-error">{connectionError}</small>}<button className="button-secondary" disabled={testing || !yahoo?.configured} onClick={testConnection}>{testing ? "Testing…" : "Test connection"}</button></div></div>
    <div className="settings-section yahoo-settings"><div className="settings-copy"><h2>Private email index</h2><p>Stores only sender, subject, date, email type and extracted order fields in your protected Supabase workspace. Bodies, HTML, attachments and Yahoo credentials stay out of the index.</p><p>An automatic sync runs once a day and keeps the index up to date on its own. Use &quot;Sync now&quot; for an immediate update or to backfill an older date range.</p><p>{index?.count || 0} metadata records indexed{index?.lastSyncedAt ? ` · last successful sync ${new Date(index.lastSyncedAt).toLocaleString()}` : ""}.</p>{index?.currentlyIndexing && <p className="status-badge"><i />Currently indexing {index.currentlyIndexing.rangeStart} to {index.currentlyIndexing.rangeEnd} (started {new Date(index.currentlyIndexing.startedAt).toLocaleString()})</p>}{index?.inProgress && <p className="status-badge"><i />In progress: {index.inProgress.rangeStart} to {index.inProgress.rangeEnd} — {index.inProgress.indexedSoFar} indexed so far, last pass {new Date(index.inProgress.lastPassAt).toLocaleString()}. Continues automatically.</p>}{index?.lastFailure && <p className="purchase-form-error">Last failed sync: {index.lastFailure.rangeStart} to {index.lastFailure.rangeEnd} at {new Date(index.lastFailure.occurredAt).toLocaleString()} — {index.lastFailure.reason || "Unknown reason."}</p>}</div><div className="index-controls"><label>From<input type="date" value={startDate} max={endDate} onChange={event => setStartDate(event.target.value)} /></label><label>To<input type="date" value={endDate} min={startDate} max={today} onChange={event => setEndDate(event.target.value)} /></label>{indexMessage && <small>{indexMessage}</small>}<button className="button-secondary" disabled={syncing || !yahoo?.configured} onClick={syncIndex}>{syncing ? "Syncing…" : "Sync now"}</button><button className="button-danger" disabled={syncing || !index?.count} onClick={clearIndex}>Clear index</button></div></div>
    <div className="settings-section yahoo-settings"><div className="settings-copy"><h2>Gmail accounts</h2><p>Connect Gmail with read-only OAuth. Connected accounts are searched alongside Yahoo by Email Assistant and Purchase Import.</p><p>Refresh tokens are encrypted server-side.</p></div><div className="yahoo-status">{gmail?.accounts.map(account=><div key={account.id}><span className="status-badge"><i />Connected</span><strong>{account.emailAddress}</strong><button className="button-danger" onClick={()=>disconnectGmail(account.id)}>Disconnect</button></div>)}{!gmail?.accounts.length&&<span className="status-badge status-off"><i />Not connected</span>}<a className="button-secondary" href="/api/gmail/connect">Connect Gmail</a>{gmail&&!gmail.configured&&<small className="purchase-form-error">Google OAuth environment variables are not configured.</small>}</div></div>
  </div></section>;
}
