import { NextResponse } from "next/server";
import { z } from "zod";
import { requireOwner } from "@/lib/auth/server";
import { safeApiError } from "@/lib/auth/api";
import { supabaseRequest, supabaseRequestAll } from "@/lib/supabase";
import { deleteVaultObjects } from "@/lib/vault-storage-server";

const kind=z.enum(["note","link","file","guide","release","private"]);
const createSchema=z.object({kind,title:z.string().trim().min(1).max(300),folder:z.string().trim().min(1).max(100),tags:z.array(z.string().trim().min(1).max(50)).max(30),content:z.string().max(1000000),url:z.string().url().optional().or(z.literal("")),releaseDate:z.string().optional(),pinned:z.boolean(),private:z.boolean()});
const patchSchema=createSchema.omit({kind:true}).partial();
type Row={id:string;kind:z.infer<typeof kind>;title:string;folder:string;tags:string[];content:string;url:string|null;release_date:string|null;pinned:boolean;private:boolean;created_at:string;updated_at:string};
type FileRow={id:string;item_id:string;name:string;size:number;mime_type:string;storage_path:string};
function item(row:Row,files:FileRow[]){return{id:row.id,kind:row.kind,title:row.title,folder:row.folder,tags:row.tags||[],content:row.content,url:row.url||undefined,releaseDate:row.release_date||undefined,pinned:row.pinned,private:row.private,createdAt:row.created_at,updatedAt:row.updated_at,attachments:files.filter(x=>x.item_id===row.id).map(x=>({id:x.id,name:x.name,size:Number(x.size),type:x.mime_type}))}}
async function owned(userId:string,id:string){const rows=await supabaseRequestAll<Row>(`vault_items?owner_id=eq.${userId}&id=eq.${encodeURIComponent(id)}&select=*&order=created_at.asc`);return rows[0]}
export async function GET(){try{const user=await requireOwner();const rows=await supabaseRequestAll<Row>(`vault_items?owner_id=eq.${user.id}&select=*&order=pinned.desc,updated_at.desc,id.desc`);const files=await supabaseRequestAll<FileRow>(`vault_attachments?owner_id=eq.${user.id}&select=id,item_id,name,size,mime_type,storage_path&order=created_at.asc`);return NextResponse.json(rows.map(x=>item(x,files)))}catch(e){return safeApiError(e,"Could not load Vault.")}}
export async function POST(request:Request){try{const user=await requireOwner(),body=createSchema.parse(await request.json());const response=await supabaseRequest("vault_items",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({owner_id:user.id,kind:body.kind,title:body.title,folder:body.folder,tags:body.tags,content:body.content,url:body.url||null,release_date:body.releaseDate||null,pinned:body.pinned,private:body.private})});const row=(await response.json() as Row[])[0];return NextResponse.json(item(row,[]),{status:201})}catch(e){return safeApiError(e,"Could not save Vault item. Run supabase-vault.sql if Vault has not been installed.")}}
export async function PATCH(request:Request){try{const user=await requireOwner(),id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Item ID is required."},{status:400});if(!await owned(user.id,id))return NextResponse.json({error:"Vault item not found."},{status:404});const body=patchSchema.parse(await request.json()),db:{[key:string]:unknown}={...body,updated_at:new Date().toISOString()};if("releaseDate"in db){db.release_date=db.releaseDate||null;delete db.releaseDate}const response=await supabaseRequest(`vault_items?id=eq.${encodeURIComponent(id)}&owner_id=eq.${user.id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(db)});const row=(await response.json() as Row[])[0];const files=await supabaseRequestAll<FileRow>(`vault_attachments?owner_id=eq.${user.id}&item_id=eq.${encodeURIComponent(id)}&select=id,item_id,name,size,mime_type,storage_path&order=created_at.asc`);return NextResponse.json(item(row,files))}catch(e){return safeApiError(e,"Could not update Vault item.")}}
export async function DELETE(request:Request){try{const user=await requireOwner(),id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Item ID is required."},{status:400});if(!await owned(user.id,id))return NextResponse.json({error:"Vault item not found."},{status:404});const files=await supabaseRequestAll<FileRow>(`vault_attachments?owner_id=eq.${user.id}&item_id=eq.${encodeURIComponent(id)}&select=id,item_id,name,size,mime_type,storage_path&order=created_at.asc`);await deleteVaultObjects(files.map(x=>x.storage_path));await supabaseRequest(`vault_items?id=eq.${encodeURIComponent(id)}&owner_id=eq.${user.id}`,{method:"DELETE"});return NextResponse.json({ok:true})}catch(e){return safeApiError(e,"Could not delete Vault item.")}}
